
#include "nuitka/prelude.h"
#include "structseq.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *Nuitka_dunder_compiled_value = NULL;

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_float_0_0;
PyObject *const_float_1_0;
PyObject *const_int_neg_1;
PyObject *const_int_neg_4;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_6;
PyObject *const_int_pos_7;
PyObject *const_int_pos_8;
PyObject *const_int_pos_9;
PyObject *const_str_chr_0;
PyObject *const_str_empty;
PyObject *const_str_space;
PyObject *const_dict_empty;
PyObject *const_int_pos_10;
PyObject *const_int_pos_11;
PyObject *const_int_pos_12;
PyObject *const_int_pos_14;
PyObject *const_int_pos_17;
PyObject *const_int_pos_18;
PyObject *const_int_pos_20;
PyObject *const_int_pos_24;
PyObject *const_int_pos_28;
PyObject *const_int_pos_32;
PyObject *const_int_pos_40;
PyObject *const_str_chr_42;
PyObject *const_int_pos_256;
PyObject *const_int_pos_536;
PyObject *const_int_pos_537;
PyObject *const_str_newline;
PyObject *const_str_plain_0;
PyObject *const_str_plain_1;
PyObject *const_str_plain_2;
PyObject *const_str_plain__;
PyObject *const_str_plain_a;
PyObject *const_str_plain_d;
PyObject *const_str_plain_e;
PyObject *const_str_plain_f;
PyObject *const_str_plain_i;
PyObject *const_str_plain_m;
PyObject *const_str_plain_r;
PyObject *const_str_plain_s;
PyObject *const_str_plain_t;
PyObject *const_str_plain_w;
PyObject *const_tuple_empty;
PyObject *const_str_plain_No;
PyObject *const_str_plain_RW;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_re;
PyObject *const_str_plain_t1;
PyObject *const_str_plain_ui;
PyObject *const_int_pos_32768;
PyObject *const_int_pos_32772;
PyObject *const_str_plain_Yes;
PyObject *const_str_plain_add;
PyObject *const_str_plain_gdk;
PyObject *const_str_plain_get;
PyObject *const_str_plain_gtk;
PyObject *const_str_plain_int;
PyObject *const_str_plain_len;
PyObject *const_str_plain_msg;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_res;
PyObject *const_str_plain_row;
PyObject *const_str_plain_run;
PyObject *const_str_plain_str;
PyObject *const_str_plain_sub;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_txt;
PyObject *const_str_plain_HBox;
PyObject *const_str_plain_None;
PyObject *const_str_plain_VBox;
PyObject *const_str_plain_args;
PyObject *const_str_plain_argv;
PyObject *const_str_plain_bool;
PyObject *const_str_plain_call;
PyObject *const_str_plain_cell;
PyObject *const_str_plain_data;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_glib;
PyObject *const_str_plain_hWnd;
PyObject *const_str_plain_hide;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_long;
PyObject *const_str_plain_m_na;
PyObject *const_str_plain_main;
PyObject *const_str_plain_mode;
PyObject *const_str_plain_name;
PyObject *const_str_plain_open;
PyObject *const_str_plain_opts;
PyObject *const_str_plain_orig;
PyObject *const_str_plain_path;
PyObject *const_str_plain_read;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_self;
PyObject *const_str_plain_show;
PyObject *const_str_plain_site;
PyObject *const_str_plain_sort;
PyObject *const_str_plain_stop;
PyObject *const_str_plain_text;
PyObject *const_str_plain_time;
PyObject *const_str_plain_type;
PyObject *const_str_plain_vbox;
PyObject *const_str_plain_warn;
PyObject *const_float_minus_0_0;
PyObject *const_float_minus_1_0;
PyObject *const_str_plain_Admin;
PyObject *const_str_plain_Drive;
PyObject *const_str_plain_Entry;
PyObject *const_str_plain_False;
PyObject *const_str_plain_IO_IN;
PyObject *const_str_plain_Label;
PyObject *const_str_plain_Linux;
PyObject *const_str_plain__glib;
PyObject *const_str_plain__name;
PyObject *const_str_plain_blkid;
PyObject *const_str_plain_c_int;
PyObject *const_str_plain_clear;
PyObject *const_str_plain_close;
PyObject *const_str_plain_count;
PyObject *const_str_plain_flags;
PyObject *const_str_plain_group;
PyObject *const_str_plain_hbox0;
PyObject *const_str_plain_index;
PyObject *const_str_plain_items;
PyObject *const_str_plain_level;
PyObject *const_str_plain_model;
PyObject *const_str_plain_mount;
PyObject *const_str_plain_popen;
PyObject *const_str_plain_query;
PyObject *const_str_plain_range;
PyObject *const_str_plain_runop;
PyObject *const_str_plain_split;
PyObject *const_str_plain_start;
PyObject *const_str_plain_strip;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_value;
PyObject *const_str_plain_win32;
PyObject *const_str_plain_write;
PyObject *const_str_angle_lambda;
PyObject *const_str_plain_Button;
PyObject *const_str_plain_DEV_OS;
PyObject *const_str_plain_GError;
PyObject *const_str_plain_IO_ERR;
PyObject *const_str_plain_IO_HUP;
PyObject *const_str_plain_IO_OUT;
PyObject *const_str_plain_IO_PRI;
PyObject *const_str_plain_LKATTR;
PyObject *const_str_plain_Thread;
PyObject *const_str_plain_Window;
PyObject *const_str_plain_append;
PyObject *const_str_plain_bad_pw;
PyObject *const_str_plain_button;
PyObject *const_str_plain_c_long;
PyObject *const_str_plain_c_uint;
PyObject *const_str_plain_ctypes;
PyObject *const_str_plain_d_list;
PyObject *const_str_plain_dev_sn;
PyObject *const_str_plain_dialog;
PyObject *const_str_plain_exists;
PyObject *const_str_plain_format;
PyObject *const_str_plain_getopt;
PyObject *const_str_plain_getter;
PyObject *const_str_plain_handle;
PyObject *const_str_plain_insert;
PyObject *const_str_plain_isfile;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_lParam;
PyObject *const_str_plain_length;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_module;
PyObject *const_str_plain_msg_ok;
PyObject *const_str_plain_object;
PyObject *const_str_plain_option;
PyObject *const_str_plain_parent;
PyObject *const_str_plain_prefix;
PyObject *const_str_plain_reboot;
PyObject *const_str_plain_remove;
PyObject *const_str_plain_search;
PyObject *const_str_plain_setter;
PyObject *const_str_plain_stdout;
PyObject *const_str_plain_string;
PyObject *const_str_plain_system;
PyObject *const_str_plain_t1_run;
PyObject *const_str_plain_target;
PyObject *const_str_plain_user32;
PyObject *const_str_plain_verify;
PyObject *const_str_plain_wParam;
PyObject *const_str_plain_warned;
PyObject *const_str_plain_windll;
PyObject *const_str_plain_window;
PyObject *const_str_plain_xrange;
PyObject *const_tuple_none_tuple;
PyObject *const_tuple_true_tuple;
PyObject *const_str_plain_GObject;
PyObject *const_str_plain_PyExtOb;
PyObject *const_str_plain_Spinner;
PyObject *const_str_plain_VERSION;
PyObject *const_str_plain_Warning;
PyObject *const_str_plain_Windows;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain_buttons;
PyObject *const_str_plain_cleanup;
PyObject *const_str_plain_clicked;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_connect;
PyObject *const_str_plain_default;
PyObject *const_str_plain_destroy;
PyObject *const_str_plain_dev_enc;
PyObject *const_str_plain_devname;
PyObject *const_str_plain_devnull;
PyObject *const_str_plain_dialogs;
PyObject *const_str_plain_dirname;
PyObject *const_str_plain_entries;
PyObject *const_str_plain_environ;
PyObject *const_str_plain_findall;
PyObject *const_str_plain_getattr;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_gobject;
PyObject *const_str_plain_handler;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_message;
PyObject *const_str_plain_modules;
PyObject *const_str_plain_msg_err;
PyObject *const_str_plain_mv_list;
PyObject *const_str_plain_openLog;
PyObject *const_str_plain_pb_menu;
PyObject *const_str_plain_prelock;
PyObject *const_str_plain_process;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_runscan;
PyObject *const_str_plain_sb_menu;
PyObject *const_str_plain_scan_ip;
PyObject *const_str_plain_sn_list;
PyObject *const_str_plain_toggled;
PyObject *const_tuple_false_tuple;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_plain_ComboBox;
PyObject *const_str_plain_G_MAXINT;
PyObject *const_str_plain_G_MININT;
PyObject *const_str_plain_PyExtLic;
PyObject *const_str_plain_TYPE_INT;
PyObject *const_str_plain_TreeIter;
PyObject *const_str_plain_TreeView;
PyObject *const_str_plain___call__;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___repr__;
PyObject *const_str_plain__gobject;
PyObject *const_str_plain_checkbox;
PyObject *const_str_plain_datetime;
PyObject *const_str_plain_dev_msid;
PyObject *const_str_plain_diskpart;
PyObject *const_str_plain_drive_na;
PyObject *const_str_plain_exc_type;
PyObject *const_str_plain_filename;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_get_text;
PyObject *const_str_plain_hib_menu;
PyObject *const_str_plain_idle_add;
PyObject *const_str_plain_kernel32;
PyObject *const_str_plain_licCheck;
PyObject *const_str_plain_lid_menu;
PyObject *const_str_plain_lockhash;
PyObject *const_str_plain_na_instr;
PyObject *const_str_plain_op_instr;
PyObject *const_str_plain_openOpal;
PyObject *const_str_plain_pack_end;
PyObject *const_str_plain_pass_dir;
PyObject *const_str_plain_pass_sav;
PyObject *const_str_plain_pba_list;
PyObject *const_str_plain_platform;
PyObject *const_str_plain_postlock;
PyObject *const_str_plain_property;
PyObject *const_str_plain_pw_strip;
PyObject *const_str_plain_run_scan;
PyObject *const_str_plain_scanning;
PyObject *const_str_plain_set_text;
PyObject *const_str_plain_show_all;
PyObject *const_str_plain_tcg_list;
PyObject *const_str_plain_usb_list;
PyObject *const_str_plain_usb_menu;
PyObject *const_str_plain_warnings;
PyObject *const_str_plain_Alignment;
PyObject *const_str_plain_G_MAXLONG;
PyObject *const_str_plain_G_MAXUINT;
PyObject *const_str_plain_G_MINLONG;
PyObject *const_str_plain_Hibernate;
PyObject *const_str_plain_ListStore;
PyObject *const_str_plain_TYPE_CHAR;
PyObject *const_str_plain_TYPE_ENUM;
PyObject *const_str_plain_TYPE_LONG;
PyObject *const_str_plain_TYPE_NONE;
PyObject *const_str_plain_TYPE_UINT;
PyObject *const_str_plain_USBDialog;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain___gtype__;
PyObject *const_str_plain_auth_menu;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_dev_setup;
PyObject *const_str_plain_devs_list;
PyObject *const_str_plain_exc_value;
PyObject *const_str_plain_get_model;
PyObject *const_str_plain_get_power;
PyObject *const_str_plain_get_value;
PyObject *const_str_plain_iter_next;
PyObject *const_str_plain_iteritems;
PyObject *const_str_plain_liststore;
PyObject *const_str_plain_main_quit;
PyObject *const_str_plain_msid_list;
PyObject *const_str_plain_runthread;
PyObject *const_str_plain_salt_list;
PyObject *const_str_plain_set_power;
PyObject *const_str_plain_set_title;
PyObject *const_str_plain_stop_spin;
PyObject *const_str_plain_threading;
PyObject *const_str_plain_user_list;
PyObject *const_str_plain_BUTTONS_OK;
PyObject *const_str_plain_G_MAXFLOAT;
PyObject *const_str_plain_G_MAXULONG;
PyObject *const_str_plain_G_MINFLOAT;
PyObject *const_str_plain_LazyModule;
PyObject *const_str_plain_TYPE_BOXED;
PyObject *const_str_plain_TYPE_FLAGS;
PyObject *const_str_plain_TYPE_FLOAT;
PyObject *const_str_plain_TYPE_INT64;
PyObject *const_str_plain_TYPE_PARAM;
PyObject *const_str_plain_TYPE_UCHAR;
PyObject *const_str_plain_TYPE_ULONG;
PyObject *const_str_plain_WM_DESTROY;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain_background;
PyObject *const_str_plain_basestring;
PyObject *const_str_plain_dev_pbaVer;
PyObject *const_str_plain_dev_select;
PyObject *const_str_plain_dev_series;
PyObject *const_str_plain_dev_status;
PyObject *const_str_plain_dev_vendor;
PyObject *const_str_plain_drive_list;
PyObject *const_str_plain_drive_menu;
PyObject *const_str_plain_get_active;
PyObject *const_str_plain_get_buffer;
PyObject *const_str_plain_pack_start;
PyObject *const_str_plain_pass_entry;
PyObject *const_str_plain_rtnHandles;
PyObject *const_str_plain_runprocess;
PyObject *const_str_plain_set_active;
PyObject *const_str_plain_set_markup;
PyObject *const_str_plain_setup_next;
PyObject *const_str_plain_show_about;
PyObject *const_str_plain_start_spin;
PyObject *const_str_plain_start_time;
PyObject *const_str_plain_subprocess;
PyObject *const_str_plain_updateDevs;
PyObject *const_str_plain_wait_instr;
PyObject *const_str_plain_CheckButton;
PyObject *const_str_plain_GObjectMeta;
PyObject *const_str_plain_GWL_WNDPROC;
PyObject *const_str_plain_G_MAXDOUBLE;
PyObject *const_str_plain_G_MINDOUBLE;
PyObject *const_str_plain_ImportError;
PyObject *const_str_plain_OptionGroup;
PyObject *const_str_plain_PBA_VERSION;
PyObject *const_str_plain_RESPONSE_OK;
PyObject *const_str_plain_TYPE_DOUBLE;
PyObject *const_str_plain_TYPE_OBJECT;
PyObject *const_str_plain_TYPE_STRING;
PyObject *const_str_plain_TYPE_UINT64;
PyObject *const_str_plain_WINFUNCTYPE;
PyObject *const_str_plain_WndProcType;
PyObject *const_str_plain__Deprecated;
PyObject *const_str_plain___delattr__;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___setattr__;
PyObject *const_str_plain__basestring;
PyObject *const_str_plain_append_text;
PyObject *const_str_plain_box_newpass;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_enable_menu;
PyObject *const_str_plain_encsup_list;
PyObject *const_str_plain_gtk_version;
PyObject *const_str_plain_hookWndProc;
PyObject *const_str_plain_locked_list;
PyObject *const_str_plain_pbawrite_ip;
PyObject *const_str_plain_screen_menu;
PyObject *const_str_plain_series_list;
PyObject *const_str_plain_timeout_add;
PyObject *const_str_plain_vendor_list;
PyObject *const_tuple_float_0_0_tuple;
PyObject *const_tuple_int_pos_1_tuple;
PyObject *const_tuple_int_pos_2_tuple;
PyObject *const_tuple_str_chr_0_tuple;
PyObject *const_tuple_str_empty_tuple;
PyObject *const_str_plain_MESSAGE_INFO;
PyObject *const_str_plain_OPTION_ERROR;
PyObject *const_str_plain_TYPE_BOOLEAN;
PyObject *const_str_plain_TYPE_POINTER;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___compiled__;
PyObject *const_str_plain_dev_blockSID;
PyObject *const_str_plain_dev_opal_ver;
PyObject *const_str_plain_disable_menu;
PyObject *const_str_plain_io_add_watch;
PyObject *const_str_plain_localWndProc;
PyObject *const_str_plain_process_list;
PyObject *const_str_plain_progress_bar;
PyObject *const_str_plain_returnToMain;
PyObject *const_str_plain_run_changePW;
PyObject *const_str_plain_run_pbaWrite;
PyObject *const_str_plain_run_setupUSB;
PyObject *const_str_plain_set_property;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_tcg_usb_list;
PyObject *const_str_plain_threads_init;
PyObject *const_str_plain_ulocked_list;
PyObject *const_str_plain_version_info;
PyObject *const_tuple_int_pos_20_tuple;
PyObject *const_tuple_str_chr_42_tuple;
PyObject *const_str_plain_LazyNamespace;
PyObject *const_str_plain_MESSAGE_ERROR;
PyObject *const_str_plain_MessageDialog;
PyObject *const_str_plain_OptionContext;
PyObject *const_str_plain_SetWindowLong;
PyObject *const_str_plain_TYPE_PYOBJECT;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain_addMsgHandler;
PyObject *const_str_plain_append_column;
PyObject *const_str_plain_blockSID_list;
PyObject *const_str_plain_cancel_button;
PyObject *const_str_plain_check_pass_rd;
PyObject *const_str_plain_define_lock_t;
PyObject *const_str_plain_dev_userSetup;
PyObject *const_str_plain_exc_traceback;
PyObject *const_str_plain_messageNumber;
PyObject *const_str_plain_op_inprogress;
PyObject *const_str_plain_opal_ver_list;
PyObject *const_str_plain_run_setupFull;
PyObject *const_str_plain_run_setupUser;
PyObject *const_str_plain_run_unlockPBA;
PyObject *const_str_plain_selected_list;
PyObject *const_str_plain_set_sensitive;
PyObject *const_str_plain_setup_prompt1;
PyObject *const_str_plain_source_remove;
PyObject *const_str_plain_unhookWndProc;
PyObject *const_str_plain_unlock_prompt;
PyObject *const_str_plain_user_aol_list;
PyObject *const_tuple_false_int_0_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_CallWindowProc;
PyObject *const_str_plain_NOT_AUTHORIZED;
PyObject *const_str_plain_PBT_APMSUSPEND;
PyObject *const_str_plain_ScrolledWindow;
PyObject *const_str_plain_SetWindowLongW;
PyObject *const_str_plain_TYPE_INTERFACE;
PyObject *const_str_plain_TreeViewColumn;
PyObject *const_str_plain_admin_aol_list;
PyObject *const_str_plain_check_box_pass;
PyObject *const_str_plain_freeze_support;
PyObject *const_str_plain_get_iter_first;
PyObject *const_str_plain_get_pspec_args;
PyObject *const_str_plain_mbr_setup_list;
PyObject *const_str_plain_new_pass_entry;
PyObject *const_str_plain_pba_wait_instr;
PyObject *const_str_plain_run_removeUser;
PyObject *const_str_plain_run_revertKeep;
PyObject *const_str_plain_run_revertPSID;
PyObject *const_str_plain_set_visibility;
PyObject *const_str_plain_setupuser_list;
PyObject *const_str_plain_CallWindowProcW;
PyObject *const_str_plain_WM_DEVICECHANGE;
PyObject *const_str_plain__default_getter;
PyObject *const_str_plain__default_setter;
PyObject *const_str_plain_ascii_uppercase;
PyObject *const_str_plain_changePW_prompt;
PyObject *const_str_plain_lockstatus_list;
PyObject *const_str_plain_mngPower_prompt;
PyObject *const_str_plain_multiprocessing;
PyObject *const_str_plain_retrylimit_list;
PyObject *const_str_plain_run_revertErase;
PyObject *const_str_plain_set_width_chars;
PyObject *const_str_plain_setupUSB_prompt;
PyObject *const_str_plain_timeout_cleanup;
PyObject *const_str_plain_CellRendererText;
PyObject *const_str_plain_OPTION_REMAINING;
PyObject *const_str_plain_WndProcHookMixin;
PyObject *const_str_plain_multi_wait_instr;
PyObject *const_str_plain_set_border_width;
PyObject *const_str_plain_set_tooltip_text;
PyObject *const_str_plain_setup_wait_instr;
PyObject *const_str_plain_setupstatus_list;
PyObject *const_str_plain_updatePBA_prompt;
PyObject *const_tuple_none_none_none_tuple;
PyObject *const_tuple_str_plain_path_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_str_plain_DBT_DEVICEARRIVAL;
PyObject *const_str_plain_WM_POWERBROADCAST;
PyObject *const_str_plain_revert_psid_entry;
PyObject *const_tuple_int_pos_3_int_0_tuple;
PyObject *const_str_plain_OPTION_FLAG_HIDDEN;
PyObject *const_str_plain_OPTION_FLAG_NO_ARG;
PyObject *const_str_plain_WM_QUERYENDSESSION;
PyObject *const_str_plain_combo_box_new_text;
PyObject *const_str_plain_confirm_pass_entry;
PyObject *const_str_plain_revert_agree_entry;
PyObject *const_str_plain_revert_keep_prompt;
PyObject *const_str_plain_set_icon_from_file;
PyObject *const_str_plain_toggleSingle_radio;
PyObject *const_str_plain_OPTION_ERROR_FAILED;
PyObject *const_str_plain_OPTION_FLAG_IN_MAIN;
PyObject *const_str_plain__DeprecatedConstant;
PyObject *const_str_plain_box_newpass_confirm;
PyObject *const_str_plain_revert_erase_prompt;
PyObject *const_str_plain_AUTHORITY_LOCKED_OUT;
PyObject *const_str_plain_DBT_DEVNODES_CHANGED;
PyObject *const_str_plain_OPTION_FLAG_FILENAME;
PyObject *const_tuple_str_plain_Hibernate_tuple;
PyObject *const_str_plain_OPTION_ERROR_BAD_VALUE;
PyObject *const_str_plain_PBT_APMRESUMEAUTOMATIC;
PyObject *const_str_plain_DBT_DEVICEREMOVECOMPLETE;
PyObject *const_str_plain_OPTION_FLAG_OPTIONAL_ARG;
PyObject *const_str_plain_DBT_DEVTYP_DEVICEINTERFACE;
PyObject *const_str_plain__WndProcHookMixin__msgDict;
PyObject *const_str_plain_OPTION_ERROR_UNKNOWN_OPTION;
PyObject *const_tuple_str_plain_ascii_uppercase_tuple;
PyObject *const_str_plain__WndProcHookMixin__oldWndProc;
PyObject *const_tuple_int_pos_1_int_0_int_0_int_0_tuple;
PyObject *const_tuple_str_plain_self_str_plain_args_tuple;
PyObject *const_str_digest_01a45f558eee63987d9de4cec604421c;
PyObject *const_str_digest_01cbd85c256bf4785aaf49c6adb60e44;
PyObject *const_str_digest_074612278ff92b03fe82846e8a94dcae;
PyObject *const_str_digest_094c260cf4b4cdff973eb04653534ba7;
PyObject *const_str_digest_0c8d3c6eed5d4373e00b3d74bc2f9bc8;
PyObject *const_str_digest_155a62777a4b4b90fb0679b817d08ceb;
PyObject *const_str_digest_1573e6b4805ac8da2565b5c6f8345d3c;
PyObject *const_str_digest_1c9b99ef582c6b5705145380d18cd593;
PyObject *const_str_digest_20f6e2e5824413a4f9d7531063b609ab;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_29fe972ddfd3c3ace7d88aee7a9cd77e;
PyObject *const_str_digest_2a99f2106e37159d649e36cd642454d7;
PyObject *const_str_digest_31eae35daa2ffa3077a1b67558489e1b;
PyObject *const_str_digest_362b9c39b7be7164b4f637e29c9f8900;
PyObject *const_str_digest_36d32a0ddc1f6851748955a073c870dd;
PyObject *const_str_digest_3d059a914d1f4299087c016a61ec41b4;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_4b8d3f96b43e55a1f0ce0c23563c4be0;
PyObject *const_str_digest_5aa1619f48b2deef896bf5b9c2af3567;
PyObject *const_str_digest_5bfaf90dbd407b4fc29090c8f6415242;
PyObject *const_str_digest_5cf0452130fc4fd9d925cac8f015f9d1;
PyObject *const_str_digest_5cf6c02bf201b8ae03ca790b05911675;
PyObject *const_str_digest_65f1ca3cc21751516d4508974112f1bb;
PyObject *const_str_digest_6eafc10dc53a14e93f58728969233d1d;
PyObject *const_str_digest_6fe42bc7767704653d0465c04f34143d;
PyObject *const_str_digest_73f4953da6c69be9cc1fa39da74e31a8;
PyObject *const_str_digest_7bb187c562694df4ba2daaaf74308c83;
PyObject *const_str_digest_7ed9dddfa3e9faf1cadc8ca7ffcfd48c;
PyObject *const_str_digest_8442ffa8f2dbdc6caf51afff829e942d;
PyObject *const_str_digest_8482c425481a7392528c91276c4d7ae3;
PyObject *const_str_digest_84ba3144e8a4c8824551fdd8d0fe5bde;
PyObject *const_str_digest_860d00cf321643e9e9ab82de992e8e2f;
PyObject *const_str_digest_89447c318e6c708927dce4c990fa5405;
PyObject *const_str_digest_8c96842b8b2bfd9741967a12c4a512ae;
PyObject *const_str_digest_8f8ffe1b3d3162a24a66f2d85dbd0368;
PyObject *const_str_digest_931335e1ae383d3cde48789cdd73233d;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_a84c2f9bb883ab000c4f334da93978e8;
PyObject *const_str_digest_ada44e9efab8574d9851f2401c97964e;
PyObject *const_str_digest_ae3b8b33bbb4f0816fc34e114de2f069;
PyObject *const_str_digest_b10cb429d790d0a06536467fb3e06959;
PyObject *const_str_digest_b27d7e3ab2e2709ddb216f1629e0528a;
PyObject *const_str_digest_be268c849f1c37b6177304e3023d15bb;
PyObject *const_str_digest_ca148312b28c30cadd5cdf7a7d84ff6d;
PyObject *const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77;
PyObject *const_str_digest_e49065392307bbeebfba0691ac0797fe;
PyObject *const_str_digest_f3d167b0dffa906401fa6c94639c194d;
PyObject *const_str_digest_f739a5f70d72101be17a94d5be764de2;
PyObject *const_str_digest_f9aa9f1d756280254529dbc306087548;
PyObject *const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0;
PyObject *const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple;
PyObject *const_tuple_8fa9613eb1d9491a5081a7a037f650ba_tuple;
PyObject *const_tuple_str_plain_c_long_str_plain_c_int_tuple;
PyObject *const_str_plain__WndProcHookMixin__localWndProcWrapped;
PyObject *const_tuple_str_digest_01a45f558eee63987d9de4cec604421c_tuple;
PyObject *const_tuple_str_digest_094c260cf4b4cdff973eb04653534ba7_tuple;
PyObject *const_tuple_str_digest_0c8d3c6eed5d4373e00b3d74bc2f9bc8_tuple;
PyObject *const_tuple_str_digest_5cf6c02bf201b8ae03ca790b05911675_tuple;
PyObject *const_tuple_str_digest_65f1ca3cc21751516d4508974112f1bb_tuple;
PyObject *const_tuple_str_digest_8482c425481a7392528c91276c4d7ae3_tuple;
PyObject *const_tuple_str_digest_84ba3144e8a4c8824551fdd8d0fe5bde_tuple;
PyObject *const_tuple_str_digest_89447c318e6c708927dce4c990fa5405_tuple;
PyObject *const_tuple_str_digest_ada44e9efab8574d9851f2401c97964e_tuple;
PyObject *const_tuple_str_digest_ae3b8b33bbb4f0816fc34e114de2f069_tuple;
PyObject *const_tuple_int_pos_1_str_digest_b10cb429d790d0a06536467fb3e06959_tuple;
PyObject *const_tuple_str_plain_self_str_plain_messageNumber_str_plain_handler_tuple;
PyObject *const_tuple_str_plain_self_str_plain_msg_str_plain_res_str_plain_message_tuple;

static void _createGlobalConstants(void) {
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyInt_FromLong(0l);
    const_str_dot = UNSTREAM_CHAR(46, 0);
    const_float_0_0 = UNSTREAM_FLOAT(&constant_bin[ 46820 ]);
    const_float_1_0 = UNSTREAM_FLOAT(&constant_bin[ 46828 ]);
    const_int_neg_1 = PyInt_FromLong(-1l);
    const_int_neg_4 = PyInt_FromLong(-4l);
    const_int_pos_1 = PyInt_FromLong(1l);
    const_int_pos_2 = PyInt_FromLong(2l);
    const_int_pos_3 = PyInt_FromLong(3l);
    const_int_pos_4 = PyInt_FromLong(4l);
    const_int_pos_5 = PyInt_FromLong(5l);
    const_int_pos_6 = PyInt_FromLong(6l);
    const_int_pos_7 = PyInt_FromLong(7l);
    const_int_pos_8 = PyInt_FromLong(8l);
    const_int_pos_9 = PyInt_FromLong(9l);
    const_str_chr_0 = UNSTREAM_CHAR(0, 0);
    const_str_empty = UNSTREAM_STRING(&constant_bin[ 0 ], 0, 0);
    const_str_space = UNSTREAM_CHAR(32, 0);
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert(PyDict_Size(const_dict_empty) == 0);
    const_int_pos_10 = PyInt_FromLong(10l);
    const_int_pos_11 = PyInt_FromLong(11l);
    const_int_pos_12 = PyInt_FromLong(12l);
    const_int_pos_14 = PyInt_FromLong(14l);
    const_int_pos_17 = PyInt_FromLong(17l);
    const_int_pos_18 = PyInt_FromLong(18l);
    const_int_pos_20 = PyInt_FromLong(20l);
    const_int_pos_24 = PyInt_FromLong(24l);
    const_int_pos_28 = PyInt_FromLong(28l);
    const_int_pos_32 = PyInt_FromLong(32l);
    const_int_pos_40 = PyInt_FromLong(40l);
    const_str_chr_42 = UNSTREAM_CHAR(42, 0);
    const_int_pos_256 = PyInt_FromLong(256l);
    const_int_pos_536 = PyInt_FromLong(536l);
    const_int_pos_537 = PyInt_FromLong(537l);
    const_str_newline = UNSTREAM_CHAR(10, 0);
    const_str_plain_0 = UNSTREAM_CHAR(48, 0);
    const_str_plain_1 = UNSTREAM_CHAR(49, 0);
    const_str_plain_2 = UNSTREAM_CHAR(50, 0);
    const_str_plain__ = UNSTREAM_CHAR(95, 1);
    const_str_plain_a = UNSTREAM_CHAR(97, 1);
    const_str_plain_d = UNSTREAM_CHAR(100, 1);
    const_str_plain_e = UNSTREAM_CHAR(101, 1);
    const_str_plain_f = UNSTREAM_CHAR(102, 1);
    const_str_plain_i = UNSTREAM_CHAR(105, 1);
    const_str_plain_m = UNSTREAM_CHAR(109, 1);
    const_str_plain_r = UNSTREAM_CHAR(114, 1);
    const_str_plain_s = UNSTREAM_CHAR(115, 1);
    const_str_plain_t = UNSTREAM_CHAR(116, 1);
    const_str_plain_w = UNSTREAM_CHAR(119, 1);
    const_tuple_empty = PyTuple_New(0);
    const_str_plain_No = UNSTREAM_STRING(&constant_bin[ 1609 ], 2, 1);
    const_str_plain_RW = UNSTREAM_STRING(&constant_bin[ 46836 ], 2, 1);
    const_str_plain_os = UNSTREAM_STRING(&constant_bin[ 361 ], 2, 1);
    const_str_plain_rb = UNSTREAM_STRING(&constant_bin[ 33435 ], 2, 1);
    const_str_plain_re = UNSTREAM_STRING(&constant_bin[ 676 ], 2, 1);
    const_str_plain_t1 = UNSTREAM_STRING(&constant_bin[ 11233 ], 2, 1);
    const_str_plain_ui = UNSTREAM_STRING(&constant_bin[ 13743 ], 2, 1);
    const_int_pos_32768 = PyInt_FromLong(32768l);
    const_int_pos_32772 = PyInt_FromLong(32772l);
    const_str_plain_Yes = UNSTREAM_STRING(&constant_bin[ 46838 ], 3, 1);
    const_str_plain_add = UNSTREAM_STRING(&constant_bin[ 7500 ], 3, 1);
    const_str_plain_gdk = UNSTREAM_STRING(&constant_bin[ 4066 ], 3, 1);
    const_str_plain_get = UNSTREAM_STRING(&constant_bin[ 1010 ], 3, 1);
    const_str_plain_gtk = UNSTREAM_STRING(&constant_bin[ 329 ], 3, 1);
    const_str_plain_int = UNSTREAM_STRING(&constant_bin[ 4392 ], 3, 1);
    const_str_plain_len = UNSTREAM_STRING(&constant_bin[ 17475 ], 3, 1);
    const_str_plain_msg = UNSTREAM_STRING(&constant_bin[ 13187 ], 3, 1);
    const_str_plain_pop = UNSTREAM_STRING(&constant_bin[ 46841 ], 3, 1);
    const_str_plain_res = UNSTREAM_STRING(&constant_bin[ 5861 ], 3, 1);
    const_str_plain_row = UNSTREAM_STRING(&constant_bin[ 19242 ], 3, 1);
    const_str_plain_run = UNSTREAM_STRING(&constant_bin[ 467 ], 3, 1);
    const_str_plain_str = UNSTREAM_STRING(&constant_bin[ 2176 ], 3, 1);
    const_str_plain_sub = UNSTREAM_STRING(&constant_bin[ 848 ], 3, 1);
    const_str_plain_sum = UNSTREAM_STRING(&constant_bin[ 15206 ], 3, 1);
    const_str_plain_sys = UNSTREAM_STRING(&constant_bin[ 217 ], 3, 1);
    const_str_plain_txt = UNSTREAM_STRING(&constant_bin[ 10929 ], 3, 1);
    const_str_plain_HBox = UNSTREAM_STRING(&constant_bin[ 46844 ], 4, 1);
    const_str_plain_None = UNSTREAM_STRING(&constant_bin[ 1609 ], 4, 1);
    const_str_plain_VBox = UNSTREAM_STRING(&constant_bin[ 46848 ], 4, 1);
    const_str_plain_args = UNSTREAM_STRING(&constant_bin[ 8429 ], 4, 1);
    const_str_plain_argv = UNSTREAM_STRING(&constant_bin[ 46852 ], 4, 1);
    const_str_plain_bool = UNSTREAM_STRING(&constant_bin[ 33037 ], 4, 1);
    const_str_plain_call = UNSTREAM_STRING(&constant_bin[ 29009 ], 4, 1);
    const_str_plain_cell = UNSTREAM_STRING(&constant_bin[ 6301 ], 4, 1);
    const_str_plain_data = UNSTREAM_STRING(&constant_bin[ 7833 ], 4, 1);
    const_str_plain_dict = UNSTREAM_STRING(&constant_bin[ 30810 ], 4, 1);
    const_str_plain_glib = UNSTREAM_STRING(&constant_bin[ 1912 ], 4, 1);
    const_str_plain_hWnd = UNSTREAM_STRING(&constant_bin[ 46856 ], 4, 1);
    const_str_plain_hide = UNSTREAM_STRING(&constant_bin[ 5577 ], 4, 1);
    const_str_plain_iter = UNSTREAM_STRING(&constant_bin[ 9804 ], 4, 1);
    const_str_plain_join = UNSTREAM_STRING(&constant_bin[ 46860 ], 4, 1);
    const_str_plain_keys = UNSTREAM_STRING(&constant_bin[ 35855 ], 4, 1);
    const_str_plain_long = UNSTREAM_STRING(&constant_bin[ 2794 ], 4, 1);
    const_str_plain_m_na = UNSTREAM_STRING(&constant_bin[ 24300 ], 4, 1);
    const_str_plain_main = UNSTREAM_STRING(&constant_bin[ 13329 ], 4, 1);
    const_str_plain_mode = UNSTREAM_STRING(&constant_bin[ 5565 ], 4, 1);
    const_str_plain_name = UNSTREAM_STRING(&constant_bin[ 7 ], 4, 1);
    const_str_plain_open = UNSTREAM_STRING(&constant_bin[ 10901 ], 4, 1);
    const_str_plain_opts = UNSTREAM_STRING(&constant_bin[ 1064 ], 4, 1);
    const_str_plain_orig = UNSTREAM_STRING(&constant_bin[ 42185 ], 4, 1);
    const_str_plain_path = UNSTREAM_STRING(&constant_bin[ 779 ], 4, 1);
    const_str_plain_read = UNSTREAM_STRING(&constant_bin[ 676 ], 4, 1);
    const_str_plain_repr = UNSTREAM_STRING(&constant_bin[ 46864 ], 4, 1);
    const_str_plain_self = UNSTREAM_STRING(&constant_bin[ 8420 ], 4, 1);
    const_str_plain_show = UNSTREAM_STRING(&constant_bin[ 9264 ], 4, 1);
    const_str_plain_site = UNSTREAM_STRING(&constant_bin[ 46868 ], 4, 1);
    const_str_plain_sort = UNSTREAM_STRING(&constant_bin[ 23540 ], 4, 1);
    const_str_plain_stop = UNSTREAM_STRING(&constant_bin[ 24634 ], 4, 1);
    const_str_plain_text = UNSTREAM_STRING(&constant_bin[ 22900 ], 4, 1);
    const_str_plain_time = UNSTREAM_STRING(&constant_bin[ 1177 ], 4, 1);
    const_str_plain_type = UNSTREAM_STRING(&constant_bin[ 911 ], 4, 1);
    const_str_plain_vbox = UNSTREAM_STRING(&constant_bin[ 13196 ], 4, 1);
    const_str_plain_warn = UNSTREAM_STRING(&constant_bin[ 4662 ], 4, 1);
    const_float_minus_0_0 = UNSTREAM_FLOAT(&constant_bin[ 46872 ]);
    const_float_minus_1_0 = UNSTREAM_FLOAT(&constant_bin[ 46880 ]);
    const_str_plain_Admin = UNSTREAM_STRING(&constant_bin[ 19074 ], 5, 1);
    const_str_plain_Drive = UNSTREAM_STRING(&constant_bin[ 5632 ], 5, 1);
    const_str_plain_Entry = UNSTREAM_STRING(&constant_bin[ 26343 ], 5, 1);
    const_str_plain_False = UNSTREAM_STRING(&constant_bin[ 2591 ], 5, 1);
    const_str_plain_IO_IN = UNSTREAM_STRING(&constant_bin[ 31513 ], 5, 1);
    const_str_plain_Label = UNSTREAM_STRING(&constant_bin[ 19337 ], 5, 1);
    const_str_plain_Linux = UNSTREAM_STRING(&constant_bin[ 46888 ], 5, 1);
    const_str_plain__glib = UNSTREAM_STRING(&constant_bin[ 1911 ], 5, 1);
    const_str_plain__name = UNSTREAM_STRING(&constant_bin[ 6340 ], 5, 1);
    const_str_plain_blkid = UNSTREAM_STRING(&constant_bin[ 46893 ], 5, 1);
    const_str_plain_c_int = UNSTREAM_STRING(&constant_bin[ 46898 ], 5, 1);
    const_str_plain_clear = UNSTREAM_STRING(&constant_bin[ 46903 ], 5, 1);
    const_str_plain_close = UNSTREAM_STRING(&constant_bin[ 22502 ], 5, 1);
    const_str_plain_count = UNSTREAM_STRING(&constant_bin[ 6615 ], 5, 1);
    const_str_plain_flags = UNSTREAM_STRING(&constant_bin[ 12114 ], 5, 1);
    const_str_plain_group = UNSTREAM_STRING(&constant_bin[ 26452 ], 5, 1);
    const_str_plain_hbox0 = UNSTREAM_STRING(&constant_bin[ 46908 ], 5, 1);
    const_str_plain_index = UNSTREAM_STRING(&constant_bin[ 23837 ], 5, 1);
    const_str_plain_items = UNSTREAM_STRING(&constant_bin[ 46913 ], 5, 1);
    const_str_plain_level = UNSTREAM_STRING(&constant_bin[ 46918 ], 5, 1);
    const_str_plain_model = UNSTREAM_STRING(&constant_bin[ 9098 ], 5, 1);
    const_str_plain_mount = UNSTREAM_STRING(&constant_bin[ 9334 ], 5, 1);
    const_str_plain_popen = UNSTREAM_STRING(&constant_bin[ 46923 ], 5, 1);
    const_str_plain_query = UNSTREAM_STRING(&constant_bin[ 19100 ], 5, 1);
    const_str_plain_range = UNSTREAM_STRING(&constant_bin[ 46928 ], 5, 1);
    const_str_plain_runop = UNSTREAM_STRING(&constant_bin[ 503 ], 5, 1);
    const_str_plain_split = UNSTREAM_STRING(&constant_bin[ 46933 ], 5, 1);
    const_str_plain_start = UNSTREAM_STRING(&constant_bin[ 1210 ], 5, 1);
    const_str_plain_strip = UNSTREAM_STRING(&constant_bin[ 40758 ], 5, 1);
    const_str_plain_tuple = UNSTREAM_STRING(&constant_bin[ 46938 ], 5, 1);
    const_str_plain_value = UNSTREAM_STRING(&constant_bin[ 6350 ], 5, 1);
    const_str_plain_win32 = UNSTREAM_STRING(&constant_bin[ 46943 ], 5, 1);
    const_str_plain_write = UNSTREAM_STRING(&constant_bin[ 8235 ], 5, 1);
    const_str_angle_lambda = UNSTREAM_STRING(&constant_bin[ 46948 ], 8, 0);
    const_str_plain_Button = UNSTREAM_STRING(&constant_bin[ 10371 ], 6, 1);
    const_str_plain_DEV_OS = UNSTREAM_STRING(&constant_bin[ 1142 ], 6, 1);
    const_str_plain_GError = UNSTREAM_STRING(&constant_bin[ 32550 ], 6, 1);
    const_str_plain_IO_ERR = UNSTREAM_STRING(&constant_bin[ 31545 ], 6, 1);
    const_str_plain_IO_HUP = UNSTREAM_STRING(&constant_bin[ 31556 ], 6, 1);
    const_str_plain_IO_OUT = UNSTREAM_STRING(&constant_bin[ 31523 ], 6, 1);
    const_str_plain_IO_PRI = UNSTREAM_STRING(&constant_bin[ 31534 ], 6, 1);
    const_str_plain_LKATTR = UNSTREAM_STRING(&constant_bin[ 46956 ], 6, 1);
    const_str_plain_Thread = UNSTREAM_STRING(&constant_bin[ 46962 ], 6, 1);
    const_str_plain_Window = UNSTREAM_STRING(&constant_bin[ 56 ], 6, 1);
    const_str_plain_append = UNSTREAM_STRING(&constant_bin[ 46968 ], 6, 1);
    const_str_plain_bad_pw = UNSTREAM_STRING(&constant_bin[ 46974 ], 6, 1);
    const_str_plain_button = UNSTREAM_STRING(&constant_bin[ 6404 ], 6, 1);
    const_str_plain_c_long = UNSTREAM_STRING(&constant_bin[ 46980 ], 6, 1);
    const_str_plain_c_uint = UNSTREAM_STRING(&constant_bin[ 46986 ], 6, 1);
    const_str_plain_ctypes = UNSTREAM_STRING(&constant_bin[ 910 ], 6, 1);
    const_str_plain_d_list = UNSTREAM_STRING(&constant_bin[ 8016 ], 6, 1);
    const_str_plain_dev_sn = UNSTREAM_STRING(&constant_bin[ 46992 ], 6, 1);
    const_str_plain_dialog = UNSTREAM_STRING(&constant_bin[ 431 ], 6, 1);
    const_str_plain_exists = UNSTREAM_STRING(&constant_bin[ 46998 ], 6, 1);
    const_str_plain_format = UNSTREAM_STRING(&constant_bin[ 6120 ], 6, 1);
    const_str_plain_getopt = UNSTREAM_STRING(&constant_bin[ 1010 ], 6, 1);
    const_str_plain_getter = UNSTREAM_STRING(&constant_bin[ 30712 ], 6, 1);
    const_str_plain_handle = UNSTREAM_STRING(&constant_bin[ 35707 ], 6, 1);
    const_str_plain_insert = UNSTREAM_STRING(&constant_bin[ 6246 ], 6, 1);
    const_str_plain_isfile = UNSTREAM_STRING(&constant_bin[ 47004 ], 6, 1);
    const_str_plain_kwargs = UNSTREAM_STRING(&constant_bin[ 47010 ], 6, 1);
    const_str_plain_lParam = UNSTREAM_STRING(&constant_bin[ 47016 ], 6, 1);
    const_str_plain_length = UNSTREAM_STRING(&constant_bin[ 24447 ], 6, 1);
    const_str_plain_locals = UNSTREAM_STRING(&constant_bin[ 36206 ], 6, 1);
    const_str_plain_module = UNSTREAM_STRING(&constant_bin[ 13310 ], 6, 1);
    const_str_plain_msg_ok = UNSTREAM_STRING(&constant_bin[ 47022 ], 6, 1);
    const_str_plain_object = UNSTREAM_STRING(&constant_bin[ 744 ], 6, 1);
    const_str_plain_option = UNSTREAM_STRING(&constant_bin[ 2690 ], 6, 1);
    const_str_plain_parent = UNSTREAM_STRING(&constant_bin[ 1282 ], 6, 1);
    const_str_plain_prefix = UNSTREAM_STRING(&constant_bin[ 47028 ], 6, 1);
    const_str_plain_reboot = UNSTREAM_STRING(&constant_bin[ 5531 ], 6, 1);
    const_str_plain_remove = UNSTREAM_STRING(&constant_bin[ 7070 ], 6, 1);
    const_str_plain_search = UNSTREAM_STRING(&constant_bin[ 47034 ], 6, 1);
    const_str_plain_setter = UNSTREAM_STRING(&constant_bin[ 30702 ], 6, 1);
    const_str_plain_stdout = UNSTREAM_STRING(&constant_bin[ 47040 ], 6, 1);
    const_str_plain_string = UNSTREAM_STRING(&constant_bin[ 2176 ], 6, 1);
    const_str_plain_system = UNSTREAM_STRING(&constant_bin[ 9475 ], 6, 1);
    const_str_plain_t1_run = UNSTREAM_STRING(&constant_bin[ 47046 ], 6, 1);
    const_str_plain_target = UNSTREAM_STRING(&constant_bin[ 47052 ], 6, 1);
    const_str_plain_user32 = UNSTREAM_STRING(&constant_bin[ 47058 ], 6, 1);
    const_str_plain_verify = UNSTREAM_STRING(&constant_bin[ 249 ], 6, 1);
    const_str_plain_wParam = UNSTREAM_STRING(&constant_bin[ 47064 ], 6, 1);
    const_str_plain_warned = UNSTREAM_STRING(&constant_bin[ 47070 ], 6, 1);
    const_str_plain_windll = UNSTREAM_STRING(&constant_bin[ 5220 ], 6, 1);
    const_str_plain_window = UNSTREAM_STRING(&constant_bin[ 47076 ], 6, 1);
    const_str_plain_xrange = UNSTREAM_STRING(&constant_bin[ 47082 ], 6, 1);
    const_tuple_none_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_none_tuple, 0, Py_None); Py_INCREF(Py_None);
    const_tuple_true_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_true_tuple, 0, Py_True); Py_INCREF(Py_True);
    const_str_plain_GObject = UNSTREAM_STRING(&constant_bin[ 1661 ], 7, 1);
    const_str_plain_PyExtOb = UNSTREAM_STRING(&constant_bin[ 47088 ], 7, 1);
    const_str_plain_Spinner = UNSTREAM_STRING(&constant_bin[ 47095 ], 7, 1);
    const_str_plain_VERSION = UNSTREAM_STRING(&constant_bin[ 1113 ], 7, 1);
    const_str_plain_Warning = UNSTREAM_STRING(&constant_bin[ 4359 ], 7, 1);
    const_str_plain_Windows = UNSTREAM_STRING(&constant_bin[ 36981 ], 7, 1);
    const_str_plain___all__ = UNSTREAM_STRING(&constant_bin[ 47102 ], 7, 1);
    const_str_plain___cmp__ = UNSTREAM_STRING(&constant_bin[ 47109 ], 7, 1);
    const_str_plain___doc__ = UNSTREAM_STRING(&constant_bin[ 47116 ], 7, 1);
    const_str_plain_buttons = UNSTREAM_STRING(&constant_bin[ 10344 ], 7, 1);
    const_str_plain_cleanup = UNSTREAM_STRING(&constant_bin[ 11549 ], 7, 1);
    const_str_plain_clicked = UNSTREAM_STRING(&constant_bin[ 47123 ], 7, 1);
    const_str_plain_compile = UNSTREAM_STRING(&constant_bin[ 4806 ], 7, 1);
    const_str_plain_connect = UNSTREAM_STRING(&constant_bin[ 47130 ], 7, 1);
    const_str_plain_default = UNSTREAM_STRING(&constant_bin[ 5681 ], 7, 1);
    const_str_plain_destroy = UNSTREAM_STRING(&constant_bin[ 8397 ], 7, 1);
    const_str_plain_dev_enc = UNSTREAM_STRING(&constant_bin[ 47137 ], 7, 1);
    const_str_plain_devname = UNSTREAM_STRING(&constant_bin[ 10490 ], 7, 1);
    const_str_plain_devnull = UNSTREAM_STRING(&constant_bin[ 47144 ], 7, 1);
    const_str_plain_dialogs = UNSTREAM_STRING(&constant_bin[ 431 ], 7, 1);
    const_str_plain_dirname = UNSTREAM_STRING(&constant_bin[ 47151 ], 7, 1);
    const_str_plain_entries = UNSTREAM_STRING(&constant_bin[ 10336 ], 7, 1);
    const_str_plain_environ = UNSTREAM_STRING(&constant_bin[ 45923 ], 7, 1);
    const_str_plain_findall = UNSTREAM_STRING(&constant_bin[ 47158 ], 7, 1);
    const_str_plain_getattr = UNSTREAM_STRING(&constant_bin[ 2369 ], 7, 1);
    const_str_plain_globals = UNSTREAM_STRING(&constant_bin[ 47165 ], 7, 1);
    const_str_plain_gobject = UNSTREAM_STRING(&constant_bin[ 743 ], 7, 1);
    const_str_plain_handler = UNSTREAM_STRING(&constant_bin[ 35707 ], 7, 1);
    const_str_plain_inspect = UNSTREAM_STRING(&constant_bin[ 47172 ], 7, 1);
    const_str_plain_message = UNSTREAM_STRING(&constant_bin[ 7049 ], 7, 1);
    const_str_plain_modules = UNSTREAM_STRING(&constant_bin[ 47179 ], 7, 1);
    const_str_plain_msg_err = UNSTREAM_STRING(&constant_bin[ 47186 ], 7, 1);
    const_str_plain_mv_list = UNSTREAM_STRING(&constant_bin[ 13643 ], 7, 1);
    const_str_plain_openLog = UNSTREAM_STRING(&constant_bin[ 10901 ], 7, 1);
    const_str_plain_pb_menu = UNSTREAM_STRING(&constant_bin[ 47193 ], 7, 1);
    const_str_plain_prelock = UNSTREAM_STRING(&constant_bin[ 5035 ], 7, 1);
    const_str_plain_process = UNSTREAM_STRING(&constant_bin[ 851 ], 7, 1);
    const_str_plain_replace = UNSTREAM_STRING(&constant_bin[ 47200 ], 7, 1);
    const_str_plain_runscan = UNSTREAM_STRING(&constant_bin[ 467 ], 7, 1);
    const_str_plain_sb_menu = UNSTREAM_STRING(&constant_bin[ 47207 ], 7, 1);
    const_str_plain_scan_ip = UNSTREAM_STRING(&constant_bin[ 47214 ], 7, 1);
    const_str_plain_sn_list = UNSTREAM_STRING(&constant_bin[ 13387 ], 7, 1);
    const_str_plain_toggled = UNSTREAM_STRING(&constant_bin[ 5570 ], 7, 1);
    const_tuple_false_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_false_tuple, 0, Py_False); Py_INCREF(Py_False);
    const_tuple_int_0_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_0_tuple, 0, const_int_0); Py_INCREF(const_int_0);
    const_str_plain_ComboBox = UNSTREAM_STRING(&constant_bin[ 47221 ], 8, 1);
    const_str_plain_G_MAXINT = UNSTREAM_STRING(&constant_bin[ 3885 ], 8, 1);
    const_str_plain_G_MININT = UNSTREAM_STRING(&constant_bin[ 3733 ], 8, 1);
    const_str_plain_PyExtLic = UNSTREAM_STRING(&constant_bin[ 47229 ], 8, 1);
    const_str_plain_TYPE_INT = UNSTREAM_STRING(&constant_bin[ 2865 ], 8, 1);
    const_str_plain_TreeIter = UNSTREAM_STRING(&constant_bin[ 47237 ], 8, 1);
    const_str_plain_TreeView = UNSTREAM_STRING(&constant_bin[ 47245 ], 8, 1);
    const_str_plain___call__ = UNSTREAM_STRING(&constant_bin[ 47253 ], 8, 1);
    const_str_plain___dict__ = UNSTREAM_STRING(&constant_bin[ 47261 ], 8, 1);
    const_str_plain___exit__ = UNSTREAM_STRING(&constant_bin[ 47269 ], 8, 1);
    const_str_plain___file__ = UNSTREAM_STRING(&constant_bin[ 5357 ], 8, 1);
    const_str_plain___init__ = UNSTREAM_STRING(&constant_bin[ 14071 ], 8, 1);
    const_str_plain___iter__ = UNSTREAM_STRING(&constant_bin[ 47277 ], 8, 1);
    const_str_plain___main__ = UNSTREAM_STRING(&constant_bin[ 47285 ], 8, 1);
    const_str_plain___name__ = UNSTREAM_STRING(&constant_bin[ 47293 ], 8, 1);
    const_str_plain___path__ = UNSTREAM_STRING(&constant_bin[ 47301 ], 8, 1);
    const_str_plain___repr__ = UNSTREAM_STRING(&constant_bin[ 47309 ], 8, 1);
    const_str_plain__gobject = UNSTREAM_STRING(&constant_bin[ 2660 ], 8, 1);
    const_str_plain_checkbox = UNSTREAM_STRING(&constant_bin[ 5557 ], 8, 1);
    const_str_plain_datetime = UNSTREAM_STRING(&constant_bin[ 1395 ], 8, 1);
    const_str_plain_dev_msid = UNSTREAM_STRING(&constant_bin[ 47317 ], 8, 1);
    const_str_plain_diskpart = UNSTREAM_STRING(&constant_bin[ 47325 ], 8, 1);
    const_str_plain_drive_na = UNSTREAM_STRING(&constant_bin[ 42299 ], 8, 1);
    const_str_plain_exc_type = UNSTREAM_STRING(&constant_bin[ 47333 ], 8, 1);
    const_str_plain_filename = UNSTREAM_STRING(&constant_bin[ 24914 ], 8, 1);
    const_str_plain_fromlist = UNSTREAM_STRING(&constant_bin[ 47341 ], 8, 1);
    const_str_plain_get_text = UNSTREAM_STRING(&constant_bin[ 47349 ], 8, 1);
    const_str_plain_hib_menu = UNSTREAM_STRING(&constant_bin[ 47357 ], 8, 1);
    const_str_plain_idle_add = UNSTREAM_STRING(&constant_bin[ 32214 ], 8, 1);
    const_str_plain_kernel32 = UNSTREAM_STRING(&constant_bin[ 45480 ], 8, 1);
    const_str_plain_licCheck = UNSTREAM_STRING(&constant_bin[ 47365 ], 8, 1);
    const_str_plain_lid_menu = UNSTREAM_STRING(&constant_bin[ 47373 ], 8, 1);
    const_str_plain_lockhash = UNSTREAM_STRING(&constant_bin[ 47381 ], 8, 1);
    const_str_plain_na_instr = UNSTREAM_STRING(&constant_bin[ 47389 ], 8, 1);
    const_str_plain_op_instr = UNSTREAM_STRING(&constant_bin[ 47397 ], 8, 1);
    const_str_plain_openOpal = UNSTREAM_STRING(&constant_bin[ 47405 ], 8, 1);
    const_str_plain_pack_end = UNSTREAM_STRING(&constant_bin[ 47413 ], 8, 1);
    const_str_plain_pass_dir = UNSTREAM_STRING(&constant_bin[ 47421 ], 8, 1);
    const_str_plain_pass_sav = UNSTREAM_STRING(&constant_bin[ 47429 ], 8, 1);
    const_str_plain_pba_list = UNSTREAM_STRING(&constant_bin[ 47437 ], 8, 1);
    const_str_plain_platform = UNSTREAM_STRING(&constant_bin[ 880 ], 8, 1);
    const_str_plain_postlock = UNSTREAM_STRING(&constant_bin[ 5071 ], 8, 1);
    const_str_plain_property = UNSTREAM_STRING(&constant_bin[ 2444 ], 8, 1);
    const_str_plain_pw_strip = UNSTREAM_STRING(&constant_bin[ 40755 ], 8, 1);
    const_str_plain_run_scan = UNSTREAM_STRING(&constant_bin[ 47445 ], 8, 1);
    const_str_plain_scanning = UNSTREAM_STRING(&constant_bin[ 47453 ], 8, 1);
    const_str_plain_set_text = UNSTREAM_STRING(&constant_bin[ 47461 ], 8, 1);
    const_str_plain_show_all = UNSTREAM_STRING(&constant_bin[ 47469 ], 8, 1);
    const_str_plain_tcg_list = UNSTREAM_STRING(&constant_bin[ 47477 ], 8, 1);
    const_str_plain_usb_list = UNSTREAM_STRING(&constant_bin[ 47485 ], 8, 1);
    const_str_plain_usb_menu = UNSTREAM_STRING(&constant_bin[ 47493 ], 8, 1);
    const_str_plain_warnings = UNSTREAM_STRING(&constant_bin[ 4662 ], 8, 1);
    const_str_plain_Alignment = UNSTREAM_STRING(&constant_bin[ 47501 ], 9, 1);
    const_str_plain_G_MAXLONG = UNSTREAM_STRING(&constant_bin[ 3922 ], 9, 1);
    const_str_plain_G_MAXUINT = UNSTREAM_STRING(&constant_bin[ 3808 ], 9, 1);
    const_str_plain_G_MINLONG = UNSTREAM_STRING(&constant_bin[ 3770 ], 9, 1);
    const_str_plain_Hibernate = UNSTREAM_STRING(&constant_bin[ 6187 ], 9, 1);
    const_str_plain_ListStore = UNSTREAM_STRING(&constant_bin[ 47510 ], 9, 1);
    const_str_plain_TYPE_CHAR = UNSTREAM_STRING(&constant_bin[ 3146 ], 9, 1);
    const_str_plain_TYPE_ENUM = UNSTREAM_STRING(&constant_bin[ 3379 ], 9, 1);
    const_str_plain_TYPE_LONG = UNSTREAM_STRING(&constant_bin[ 2827 ], 9, 1);
    const_str_plain_TYPE_NONE = UNSTREAM_STRING(&constant_bin[ 3065 ], 9, 1);
    const_str_plain_TYPE_UINT = UNSTREAM_STRING(&constant_bin[ 2718 ], 9, 1);
    const_str_plain_USBDialog = UNSTREAM_STRING(&constant_bin[ 47519 ], 9, 1);
    const_str_plain___class__ = UNSTREAM_STRING(&constant_bin[ 47528 ], 9, 1);
    const_str_plain___debug__ = UNSTREAM_STRING(&constant_bin[ 47537 ], 9, 1);
    const_str_plain___enter__ = UNSTREAM_STRING(&constant_bin[ 47546 ], 9, 1);
    const_str_plain___gtype__ = UNSTREAM_STRING(&constant_bin[ 47555 ], 9, 1);
    const_str_plain_auth_menu = UNSTREAM_STRING(&constant_bin[ 47564 ], 9, 1);
    const_str_plain_bytearray = UNSTREAM_STRING(&constant_bin[ 47573 ], 9, 1);
    const_str_plain_dev_setup = UNSTREAM_STRING(&constant_bin[ 47582 ], 9, 1);
    const_str_plain_devs_list = UNSTREAM_STRING(&constant_bin[ 13247 ], 9, 1);
    const_str_plain_exc_value = UNSTREAM_STRING(&constant_bin[ 47591 ], 9, 1);
    const_str_plain_get_model = UNSTREAM_STRING(&constant_bin[ 47600 ], 9, 1);
    const_str_plain_get_power = UNSTREAM_STRING(&constant_bin[ 47609 ], 9, 1);
    const_str_plain_get_value = UNSTREAM_STRING(&constant_bin[ 47618 ], 9, 1);
    const_str_plain_iter_next = UNSTREAM_STRING(&constant_bin[ 47627 ], 9, 1);
    const_str_plain_iteritems = UNSTREAM_STRING(&constant_bin[ 47636 ], 9, 1);
    const_str_plain_liststore = UNSTREAM_STRING(&constant_bin[ 47645 ], 9, 1);
    const_str_plain_main_quit = UNSTREAM_STRING(&constant_bin[ 47654 ], 9, 1);
    const_str_plain_msid_list = UNSTREAM_STRING(&constant_bin[ 47663 ], 9, 1);
    const_str_plain_runthread = UNSTREAM_STRING(&constant_bin[ 1317 ], 9, 1);
    const_str_plain_salt_list = UNSTREAM_STRING(&constant_bin[ 9177 ], 9, 1);
    const_str_plain_set_power = UNSTREAM_STRING(&constant_bin[ 47672 ], 9, 1);
    const_str_plain_set_title = UNSTREAM_STRING(&constant_bin[ 47681 ], 9, 1);
    const_str_plain_stop_spin = UNSTREAM_STRING(&constant_bin[ 47690 ], 9, 1);
    const_str_plain_threading = UNSTREAM_STRING(&constant_bin[ 674 ], 9, 1);
    const_str_plain_user_list = UNSTREAM_STRING(&constant_bin[ 10386 ], 9, 1);
    const_str_plain_BUTTONS_OK = UNSTREAM_STRING(&constant_bin[ 42358 ], 10, 1);
    const_str_plain_G_MAXFLOAT = UNSTREAM_STRING(&constant_bin[ 3654 ], 10, 1);
    const_str_plain_G_MAXULONG = UNSTREAM_STRING(&constant_bin[ 3846 ], 10, 1);
    const_str_plain_G_MINFLOAT = UNSTREAM_STRING(&constant_bin[ 47699 ], 10, 1);
    const_str_plain_LazyModule = UNSTREAM_STRING(&constant_bin[ 4145 ], 10, 1);
    const_str_plain_TYPE_BOXED = UNSTREAM_STRING(&constant_bin[ 3536 ], 10, 1);
    const_str_plain_TYPE_FLAGS = UNSTREAM_STRING(&constant_bin[ 3417 ], 10, 1);
    const_str_plain_TYPE_FLOAT = UNSTREAM_STRING(&constant_bin[ 3456 ], 10, 1);
    const_str_plain_TYPE_INT64 = UNSTREAM_STRING(&constant_bin[ 3300 ], 10, 1);
    const_str_plain_TYPE_PARAM = UNSTREAM_STRING(&constant_bin[ 3575 ], 10, 1);
    const_str_plain_TYPE_UCHAR = UNSTREAM_STRING(&constant_bin[ 3184 ], 10, 1);
    const_str_plain_TYPE_ULONG = UNSTREAM_STRING(&constant_bin[ 3261 ], 10, 1);
    const_str_plain_WM_DESTROY = UNSTREAM_STRING(&constant_bin[ 135 ], 10, 1);
    const_str_plain___import__ = UNSTREAM_STRING(&constant_bin[ 47709 ], 10, 1);
    const_str_plain___module__ = UNSTREAM_STRING(&constant_bin[ 47719 ], 10, 1);
    const_str_plain_background = UNSTREAM_STRING(&constant_bin[ 392 ], 10, 1);
    const_str_plain_basestring = UNSTREAM_STRING(&constant_bin[ 2172 ], 10, 1);
    const_str_plain_dev_pbaVer = UNSTREAM_STRING(&constant_bin[ 47729 ], 10, 1);
    const_str_plain_dev_select = UNSTREAM_STRING(&constant_bin[ 47739 ], 10, 1);
    const_str_plain_dev_series = UNSTREAM_STRING(&constant_bin[ 47749 ], 10, 1);
    const_str_plain_dev_status = UNSTREAM_STRING(&constant_bin[ 47759 ], 10, 1);
    const_str_plain_dev_vendor = UNSTREAM_STRING(&constant_bin[ 47769 ], 10, 1);
    const_str_plain_drive_list = UNSTREAM_STRING(&constant_bin[ 44548 ], 10, 1);
    const_str_plain_drive_menu = UNSTREAM_STRING(&constant_bin[ 47779 ], 10, 1);
    const_str_plain_get_active = UNSTREAM_STRING(&constant_bin[ 40147 ], 10, 1);
    const_str_plain_get_buffer = UNSTREAM_STRING(&constant_bin[ 47789 ], 10, 1);
    const_str_plain_pack_start = UNSTREAM_STRING(&constant_bin[ 47799 ], 10, 1);
    const_str_plain_pass_entry = UNSTREAM_STRING(&constant_bin[ 47809 ], 10, 1);
    const_str_plain_rtnHandles = UNSTREAM_STRING(&constant_bin[ 47819 ], 10, 1);
    const_str_plain_runprocess = UNSTREAM_STRING(&constant_bin[ 5145 ], 10, 1);
    const_str_plain_set_active = UNSTREAM_STRING(&constant_bin[ 47829 ], 10, 1);
    const_str_plain_set_markup = UNSTREAM_STRING(&constant_bin[ 47839 ], 10, 1);
    const_str_plain_setup_next = UNSTREAM_STRING(&constant_bin[ 47849 ], 10, 1);
    const_str_plain_show_about = UNSTREAM_STRING(&constant_bin[ 47859 ], 10, 1);
    const_str_plain_start_spin = UNSTREAM_STRING(&constant_bin[ 47869 ], 10, 1);
    const_str_plain_start_time = UNSTREAM_STRING(&constant_bin[ 14970 ], 10, 1);
    const_str_plain_subprocess = UNSTREAM_STRING(&constant_bin[ 848 ], 10, 1);
    const_str_plain_updateDevs = UNSTREAM_STRING(&constant_bin[ 47879 ], 10, 1);
    const_str_plain_wait_instr = UNSTREAM_STRING(&constant_bin[ 47889 ], 10, 1);
    const_str_plain_CheckButton = UNSTREAM_STRING(&constant_bin[ 47899 ], 11, 1);
    const_str_plain_GObjectMeta = UNSTREAM_STRING(&constant_bin[ 1661 ], 11, 1);
    const_str_plain_GWL_WNDPROC = UNSTREAM_STRING(&constant_bin[ 95 ], 11, 1);
    const_str_plain_G_MAXDOUBLE = UNSTREAM_STRING(&constant_bin[ 3693 ], 11, 1);
    const_str_plain_G_MINDOUBLE = UNSTREAM_STRING(&constant_bin[ 47910 ], 11, 1);
    const_str_plain_ImportError = UNSTREAM_STRING(&constant_bin[ 1576 ], 11, 1);
    const_str_plain_OptionGroup = UNSTREAM_STRING(&constant_bin[ 2211 ], 11, 1);
    const_str_plain_PBA_VERSION = UNSTREAM_STRING(&constant_bin[ 13355 ], 11, 1);
    const_str_plain_RESPONSE_OK = UNSTREAM_STRING(&constant_bin[ 47921 ], 11, 1);
    const_str_plain_TYPE_DOUBLE = UNSTREAM_STRING(&constant_bin[ 2943 ], 11, 1);
    const_str_plain_TYPE_OBJECT = UNSTREAM_STRING(&constant_bin[ 3614 ], 11, 1);
    const_str_plain_TYPE_STRING = UNSTREAM_STRING(&constant_bin[ 2983 ], 11, 1);
    const_str_plain_TYPE_UINT64 = UNSTREAM_STRING(&constant_bin[ 3339 ], 11, 1);
    const_str_plain_WINFUNCTYPE = UNSTREAM_STRING(&constant_bin[ 47932 ], 11, 1);
    const_str_plain_WndProcType = UNSTREAM_STRING(&constant_bin[ 13 ], 11, 1);
    const_str_plain__Deprecated = UNSTREAM_STRING(&constant_bin[ 4259 ], 11, 1);
    const_str_plain___delattr__ = UNSTREAM_STRING(&constant_bin[ 47943 ], 11, 1);
    const_str_plain___getattr__ = UNSTREAM_STRING(&constant_bin[ 47954 ], 11, 1);
    const_str_plain___package__ = UNSTREAM_STRING(&constant_bin[ 47965 ], 11, 1);
    const_str_plain___setattr__ = UNSTREAM_STRING(&constant_bin[ 47976 ], 11, 1);
    const_str_plain__basestring = UNSTREAM_STRING(&constant_bin[ 2171 ], 11, 1);
    const_str_plain_append_text = UNSTREAM_STRING(&constant_bin[ 47987 ], 11, 1);
    const_str_plain_box_newpass = UNSTREAM_STRING(&constant_bin[ 47998 ], 11, 1);
    const_str_plain_classmethod = UNSTREAM_STRING(&constant_bin[ 48009 ], 11, 1);
    const_str_plain_enable_menu = UNSTREAM_STRING(&constant_bin[ 48020 ], 11, 1);
    const_str_plain_encsup_list = UNSTREAM_STRING(&constant_bin[ 48031 ], 11, 1);
    const_str_plain_gtk_version = UNSTREAM_STRING(&constant_bin[ 48042 ], 11, 1);
    const_str_plain_hookWndProc = UNSTREAM_STRING(&constant_bin[ 48053 ], 11, 1);
    const_str_plain_locked_list = UNSTREAM_STRING(&constant_bin[ 48064 ], 11, 1);
    const_str_plain_pbawrite_ip = UNSTREAM_STRING(&constant_bin[ 48075 ], 11, 1);
    const_str_plain_screen_menu = UNSTREAM_STRING(&constant_bin[ 48086 ], 11, 1);
    const_str_plain_series_list = UNSTREAM_STRING(&constant_bin[ 48097 ], 11, 1);
    const_str_plain_timeout_add = UNSTREAM_STRING(&constant_bin[ 32227 ], 11, 1);
    const_str_plain_vendor_list = UNSTREAM_STRING(&constant_bin[ 48108 ], 11, 1);
    const_tuple_float_0_0_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_float_0_0_tuple, 0, const_float_0_0); Py_INCREF(const_float_0_0);
    const_tuple_int_pos_1_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_pos_1_tuple, 0, const_int_pos_1); Py_INCREF(const_int_pos_1);
    const_tuple_int_pos_2_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_pos_2_tuple, 0, const_int_pos_2); Py_INCREF(const_int_pos_2);
    const_tuple_str_chr_0_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_chr_0_tuple, 0, const_str_chr_0); Py_INCREF(const_str_chr_0);
    const_tuple_str_empty_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_empty_tuple, 0, const_str_empty); Py_INCREF(const_str_empty);
    const_str_plain_MESSAGE_INFO = UNSTREAM_STRING(&constant_bin[ 48119 ], 12, 1);
    const_str_plain_OPTION_ERROR = UNSTREAM_STRING(&constant_bin[ 32002 ], 12, 1);
    const_str_plain_TYPE_BOOLEAN = UNSTREAM_STRING(&constant_bin[ 2902 ], 12, 1);
    const_str_plain_TYPE_POINTER = UNSTREAM_STRING(&constant_bin[ 3495 ], 12, 1);
    const_str_plain___builtins__ = UNSTREAM_STRING(&constant_bin[ 48131 ], 12, 1);
    const_str_plain___compiled__ = UNSTREAM_STRING(&constant_bin[ 48143 ], 12, 1);
    const_str_plain_dev_blockSID = UNSTREAM_STRING(&constant_bin[ 48155 ], 12, 1);
    const_str_plain_dev_opal_ver = UNSTREAM_STRING(&constant_bin[ 48167 ], 12, 1);
    const_str_plain_disable_menu = UNSTREAM_STRING(&constant_bin[ 48179 ], 12, 1);
    const_str_plain_io_add_watch = UNSTREAM_STRING(&constant_bin[ 32267 ], 12, 1);
    const_str_plain_localWndProc = UNSTREAM_STRING(&constant_bin[ 48191 ], 12, 1);
    const_str_plain_process_list = UNSTREAM_STRING(&constant_bin[ 48203 ], 12, 1);
    const_str_plain_progress_bar = UNSTREAM_STRING(&constant_bin[ 48215 ], 12, 1);
    const_str_plain_returnToMain = UNSTREAM_STRING(&constant_bin[ 48227 ], 12, 1);
    const_str_plain_run_changePW = UNSTREAM_STRING(&constant_bin[ 48239 ], 12, 1);
    const_str_plain_run_pbaWrite = UNSTREAM_STRING(&constant_bin[ 48251 ], 12, 1);
    const_str_plain_run_setupUSB = UNSTREAM_STRING(&constant_bin[ 48263 ], 12, 1);
    const_str_plain_set_property = UNSTREAM_STRING(&constant_bin[ 30646 ], 12, 1);
    const_str_plain_staticmethod = UNSTREAM_STRING(&constant_bin[ 48275 ], 12, 1);
    const_str_plain_tcg_usb_list = UNSTREAM_STRING(&constant_bin[ 48287 ], 12, 1);
    const_str_plain_threads_init = UNSTREAM_STRING(&constant_bin[ 48299 ], 12, 1);
    const_str_plain_ulocked_list = UNSTREAM_STRING(&constant_bin[ 48311 ], 12, 1);
    const_str_plain_version_info = UNSTREAM_STRING(&constant_bin[ 48323 ], 12, 1);
    const_tuple_int_pos_20_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_pos_20_tuple, 0, const_int_pos_20); Py_INCREF(const_int_pos_20);
    const_tuple_str_chr_42_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_chr_42_tuple, 0, const_str_chr_42); Py_INCREF(const_str_chr_42);
    const_str_plain_LazyNamespace = UNSTREAM_STRING(&constant_bin[ 4544 ], 13, 1);
    const_str_plain_MESSAGE_ERROR = UNSTREAM_STRING(&constant_bin[ 48335 ], 13, 1);
    const_str_plain_MessageDialog = UNSTREAM_STRING(&constant_bin[ 48348 ], 13, 1);
    const_str_plain_OptionContext = UNSTREAM_STRING(&constant_bin[ 26354 ], 13, 1);
    const_str_plain_SetWindowLong = UNSTREAM_STRING(&constant_bin[ 53 ], 13, 1);
    const_str_plain_TYPE_PYOBJECT = UNSTREAM_STRING(&constant_bin[ 3023 ], 13, 1);
    const_str_plain___metaclass__ = UNSTREAM_STRING(&constant_bin[ 938 ], 13, 1);
    const_str_plain_addMsgHandler = UNSTREAM_STRING(&constant_bin[ 48361 ], 13, 1);
    const_str_plain_append_column = UNSTREAM_STRING(&constant_bin[ 48374 ], 13, 1);
    const_str_plain_blockSID_list = UNSTREAM_STRING(&constant_bin[ 48387 ], 13, 1);
    const_str_plain_cancel_button = UNSTREAM_STRING(&constant_bin[ 48400 ], 13, 1);
    const_str_plain_check_pass_rd = UNSTREAM_STRING(&constant_bin[ 48413 ], 13, 1);
    const_str_plain_define_lock_t = UNSTREAM_STRING(&constant_bin[ 48426 ], 13, 1);
    const_str_plain_dev_userSetup = UNSTREAM_STRING(&constant_bin[ 48439 ], 13, 1);
    const_str_plain_exc_traceback = UNSTREAM_STRING(&constant_bin[ 48452 ], 13, 1);
    const_str_plain_messageNumber = UNSTREAM_STRING(&constant_bin[ 48465 ], 13, 1);
    const_str_plain_op_inprogress = UNSTREAM_STRING(&constant_bin[ 48478 ], 13, 1);
    const_str_plain_opal_ver_list = UNSTREAM_STRING(&constant_bin[ 48491 ], 13, 1);
    const_str_plain_run_setupFull = UNSTREAM_STRING(&constant_bin[ 48504 ], 13, 1);
    const_str_plain_run_setupUser = UNSTREAM_STRING(&constant_bin[ 48517 ], 13, 1);
    const_str_plain_run_unlockPBA = UNSTREAM_STRING(&constant_bin[ 48530 ], 13, 1);
    const_str_plain_selected_list = UNSTREAM_STRING(&constant_bin[ 15022 ], 13, 1);
    const_str_plain_set_sensitive = UNSTREAM_STRING(&constant_bin[ 48543 ], 13, 1);
    const_str_plain_setup_prompt1 = UNSTREAM_STRING(&constant_bin[ 48556 ], 13, 1);
    const_str_plain_source_remove = UNSTREAM_STRING(&constant_bin[ 32284 ], 13, 1);
    const_str_plain_unhookWndProc = UNSTREAM_STRING(&constant_bin[ 48569 ], 13, 1);
    const_str_plain_unlock_prompt = UNSTREAM_STRING(&constant_bin[ 48582 ], 13, 1);
    const_str_plain_user_aol_list = UNSTREAM_STRING(&constant_bin[ 48595 ], 13, 1);
    const_tuple_false_int_0_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_false_int_0_tuple, 0, Py_False); Py_INCREF(Py_False);
    PyTuple_SET_ITEM(const_tuple_false_int_0_tuple, 1, const_int_0); Py_INCREF(const_int_0);
    const_tuple_type_object_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type); Py_INCREF((PyObject *)&PyBaseObject_Type);
    const_str_plain_CallWindowProc = UNSTREAM_STRING(&constant_bin[ 174 ], 14, 1);
    const_str_plain_NOT_AUTHORIZED = UNSTREAM_STRING(&constant_bin[ 48608 ], 14, 1);
    const_str_plain_PBT_APMSUSPEND = UNSTREAM_STRING(&constant_bin[ 48622 ], 14, 1);
    const_str_plain_ScrolledWindow = UNSTREAM_STRING(&constant_bin[ 48636 ], 14, 1);
    const_str_plain_SetWindowLongW = UNSTREAM_STRING(&constant_bin[ 48650 ], 14, 1);
    const_str_plain_TYPE_INTERFACE = UNSTREAM_STRING(&constant_bin[ 3103 ], 14, 1);
    const_str_plain_TreeViewColumn = UNSTREAM_STRING(&constant_bin[ 48664 ], 14, 1);
    const_str_plain_admin_aol_list = UNSTREAM_STRING(&constant_bin[ 48678 ], 14, 1);
    const_str_plain_check_box_pass = UNSTREAM_STRING(&constant_bin[ 12689 ], 14, 1);
    const_str_plain_freeze_support = UNSTREAM_STRING(&constant_bin[ 48692 ], 14, 1);
    const_str_plain_get_iter_first = UNSTREAM_STRING(&constant_bin[ 48706 ], 14, 1);
    const_str_plain_get_pspec_args = UNSTREAM_STRING(&constant_bin[ 48720 ], 14, 1);
    const_str_plain_mbr_setup_list = UNSTREAM_STRING(&constant_bin[ 48734 ], 14, 1);
    const_str_plain_new_pass_entry = UNSTREAM_STRING(&constant_bin[ 48748 ], 14, 1);
    const_str_plain_pba_wait_instr = UNSTREAM_STRING(&constant_bin[ 48762 ], 14, 1);
    const_str_plain_run_removeUser = UNSTREAM_STRING(&constant_bin[ 48776 ], 14, 1);
    const_str_plain_run_revertKeep = UNSTREAM_STRING(&constant_bin[ 48790 ], 14, 1);
    const_str_plain_run_revertPSID = UNSTREAM_STRING(&constant_bin[ 48804 ], 14, 1);
    const_str_plain_set_visibility = UNSTREAM_STRING(&constant_bin[ 48818 ], 14, 1);
    const_str_plain_setupuser_list = UNSTREAM_STRING(&constant_bin[ 48832 ], 14, 1);
    const_str_plain_CallWindowProcW = UNSTREAM_STRING(&constant_bin[ 48846 ], 15, 1);
    const_str_plain_WM_DEVICECHANGE = UNSTREAM_STRING(&constant_bin[ 537 ], 15, 1);
    const_str_plain__default_getter = UNSTREAM_STRING(&constant_bin[ 48861 ], 15, 1);
    const_str_plain__default_setter = UNSTREAM_STRING(&constant_bin[ 48876 ], 15, 1);
    const_str_plain_ascii_uppercase = UNSTREAM_STRING(&constant_bin[ 48891 ], 15, 1);
    const_str_plain_changePW_prompt = UNSTREAM_STRING(&constant_bin[ 48906 ], 15, 1);
    const_str_plain_lockstatus_list = UNSTREAM_STRING(&constant_bin[ 48921 ], 15, 1);
    const_str_plain_mngPower_prompt = UNSTREAM_STRING(&constant_bin[ 48936 ], 15, 1);
    const_str_plain_multiprocessing = UNSTREAM_STRING(&constant_bin[ 973 ], 15, 1);
    const_str_plain_retrylimit_list = UNSTREAM_STRING(&constant_bin[ 48951 ], 15, 1);
    const_str_plain_run_revertErase = UNSTREAM_STRING(&constant_bin[ 48966 ], 15, 1);
    const_str_plain_set_width_chars = UNSTREAM_STRING(&constant_bin[ 48981 ], 15, 1);
    const_str_plain_setupUSB_prompt = UNSTREAM_STRING(&constant_bin[ 48996 ], 15, 1);
    const_str_plain_timeout_cleanup = UNSTREAM_STRING(&constant_bin[ 49011 ], 15, 1);
    const_str_plain_CellRendererText = UNSTREAM_STRING(&constant_bin[ 49026 ], 16, 1);
    const_str_plain_OPTION_REMAINING = UNSTREAM_STRING(&constant_bin[ 32085 ], 16, 1);
    const_str_plain_WndProcHookMixin = UNSTREAM_STRING(&constant_bin[ 284 ], 16, 1);
    const_str_plain_multi_wait_instr = UNSTREAM_STRING(&constant_bin[ 49042 ], 16, 1);
    const_str_plain_set_border_width = UNSTREAM_STRING(&constant_bin[ 49058 ], 16, 1);
    const_str_plain_set_tooltip_text = UNSTREAM_STRING(&constant_bin[ 49074 ], 16, 1);
    const_str_plain_setup_wait_instr = UNSTREAM_STRING(&constant_bin[ 49090 ], 16, 1);
    const_str_plain_setupstatus_list = UNSTREAM_STRING(&constant_bin[ 49106 ], 16, 1);
    const_str_plain_updatePBA_prompt = UNSTREAM_STRING(&constant_bin[ 49122 ], 16, 1);
    const_tuple_none_none_none_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 0, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 1, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 2, Py_None); Py_INCREF(Py_None);
    const_tuple_str_plain_path_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_path_tuple, 0, const_str_plain_path); Py_INCREF(const_str_plain_path);
    const_tuple_str_plain_self_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    const_str_plain_DBT_DEVICEARRIVAL = UNSTREAM_STRING(&constant_bin[ 49138 ], 17, 1);
    const_str_plain_WM_POWERBROADCAST = UNSTREAM_STRING(&constant_bin[ 581 ], 17, 1);
    const_str_plain_revert_psid_entry = UNSTREAM_STRING(&constant_bin[ 49155 ], 17, 1);
    const_tuple_int_pos_3_int_0_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_int_pos_3_int_0_tuple, 0, const_int_pos_3); Py_INCREF(const_int_pos_3);
    PyTuple_SET_ITEM(const_tuple_int_pos_3_int_0_tuple, 1, const_int_0); Py_INCREF(const_int_0);
    const_str_plain_OPTION_FLAG_HIDDEN = UNSTREAM_STRING(&constant_bin[ 31830 ], 18, 1);
    const_str_plain_OPTION_FLAG_NO_ARG = UNSTREAM_STRING(&constant_bin[ 31901 ], 18, 1);
    const_str_plain_WM_QUERYENDSESSION = UNSTREAM_STRING(&constant_bin[ 627 ], 18, 1);
    const_str_plain_combo_box_new_text = UNSTREAM_STRING(&constant_bin[ 49172 ], 18, 1);
    const_str_plain_confirm_pass_entry = UNSTREAM_STRING(&constant_bin[ 49190 ], 18, 1);
    const_str_plain_revert_agree_entry = UNSTREAM_STRING(&constant_bin[ 49208 ], 18, 1);
    const_str_plain_revert_keep_prompt = UNSTREAM_STRING(&constant_bin[ 49226 ], 18, 1);
    const_str_plain_set_icon_from_file = UNSTREAM_STRING(&constant_bin[ 49244 ], 18, 1);
    const_str_plain_toggleSingle_radio = UNSTREAM_STRING(&constant_bin[ 49262 ], 18, 1);
    const_str_plain_OPTION_ERROR_FAILED = UNSTREAM_STRING(&constant_bin[ 32061 ], 19, 1);
    const_str_plain_OPTION_FLAG_IN_MAIN = UNSTREAM_STRING(&constant_bin[ 31853 ], 19, 1);
    const_str_plain__DeprecatedConstant = UNSTREAM_STRING(&constant_bin[ 4292 ], 19, 1);
    const_str_plain_box_newpass_confirm = UNSTREAM_STRING(&constant_bin[ 49280 ], 19, 1);
    const_str_plain_revert_erase_prompt = UNSTREAM_STRING(&constant_bin[ 49299 ], 19, 1);
    const_str_plain_AUTHORITY_LOCKED_OUT = UNSTREAM_STRING(&constant_bin[ 49318 ], 20, 1);
    const_str_plain_DBT_DEVNODES_CHANGED = UNSTREAM_STRING(&constant_bin[ 49338 ], 20, 1);
    const_str_plain_OPTION_FLAG_FILENAME = UNSTREAM_STRING(&constant_bin[ 31924 ], 20, 1);
    const_tuple_str_plain_Hibernate_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_Hibernate_tuple, 0, const_str_plain_Hibernate); Py_INCREF(const_str_plain_Hibernate);
    const_str_plain_OPTION_ERROR_BAD_VALUE = UNSTREAM_STRING(&constant_bin[ 32034 ], 22, 1);
    const_str_plain_PBT_APMRESUMEAUTOMATIC = UNSTREAM_STRING(&constant_bin[ 49358 ], 22, 1);
    const_str_plain_DBT_DEVICEREMOVECOMPLETE = UNSTREAM_STRING(&constant_bin[ 49380 ], 24, 1);
    const_str_plain_OPTION_FLAG_OPTIONAL_ARG = UNSTREAM_STRING(&constant_bin[ 31949 ], 24, 1);
    const_str_plain_DBT_DEVTYP_DEVICEINTERFACE = UNSTREAM_STRING(&constant_bin[ 49404 ], 26, 1);
    const_str_plain__WndProcHookMixin__msgDict = UNSTREAM_STRING(&constant_bin[ 49430 ], 26, 1);
    const_str_plain_OPTION_ERROR_UNKNOWN_OPTION = UNSTREAM_STRING(&constant_bin[ 32002 ], 27, 1);
    const_tuple_str_plain_ascii_uppercase_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_ascii_uppercase_tuple, 0, const_str_plain_ascii_uppercase); Py_INCREF(const_str_plain_ascii_uppercase);
    const_str_plain__WndProcHookMixin__oldWndProc = UNSTREAM_STRING(&constant_bin[ 49456 ], 29, 1);
    const_tuple_int_pos_1_int_0_int_0_int_0_tuple = PyTuple_New(4);
    PyTuple_SET_ITEM(const_tuple_int_pos_1_int_0_int_0_int_0_tuple, 0, const_int_pos_1); Py_INCREF(const_int_pos_1);
    PyTuple_SET_ITEM(const_tuple_int_pos_1_int_0_int_0_int_0_tuple, 1, const_int_0); Py_INCREF(const_int_0);
    PyTuple_SET_ITEM(const_tuple_int_pos_1_int_0_int_0_int_0_tuple, 2, const_int_0); Py_INCREF(const_int_0);
    PyTuple_SET_ITEM(const_tuple_int_pos_1_int_0_int_0_int_0_tuple, 3, const_int_0); Py_INCREF(const_int_0);
    const_tuple_str_plain_self_str_plain_args_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_args_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_args_tuple, 1, const_str_plain_args); Py_INCREF(const_str_plain_args);
    const_str_digest_01a45f558eee63987d9de4cec604421c = UNSTREAM_STRING(&constant_bin[ 49485 ], 59, 0);
    const_str_digest_01cbd85c256bf4785aaf49c6adb60e44 = UNSTREAM_STRING(&constant_bin[ 49544 ], 12, 0);
    const_str_digest_074612278ff92b03fe82846e8a94dcae = UNSTREAM_STRING(&constant_bin[ 36275 ], 15, 0);
    const_str_digest_094c260cf4b4cdff973eb04653534ba7 = UNSTREAM_STRING(&constant_bin[ 49556 ], 22, 0);
    const_str_digest_0c8d3c6eed5d4373e00b3d74bc2f9bc8 = UNSTREAM_STRING(&constant_bin[ 49578 ], 130, 0);
    const_str_digest_155a62777a4b4b90fb0679b817d08ceb = UNSTREAM_STRING(&constant_bin[ 49708 ], 8, 0);
    const_str_digest_1573e6b4805ac8da2565b5c6f8345d3c = UNSTREAM_STRING(&constant_bin[ 49716 ], 18, 0);
    const_str_digest_1c9b99ef582c6b5705145380d18cd593 = UNSTREAM_STRING(&constant_bin[ 49734 ], 23, 0);
    const_str_digest_20f6e2e5824413a4f9d7531063b609ab = UNSTREAM_STRING(&constant_bin[ 49757 ], 10, 0);
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING(&constant_bin[ 28394 ], 2, 0);
    const_str_digest_29fe972ddfd3c3ace7d88aee7a9cd77e = UNSTREAM_STRING(&constant_bin[ 13376 ], 2, 0);
    const_str_digest_2a99f2106e37159d649e36cd642454d7 = UNSTREAM_STRING(&constant_bin[ 11237 ], 2, 0);
    const_str_digest_31eae35daa2ffa3077a1b67558489e1b = UNSTREAM_STRING(&constant_bin[ 49767 ], 22, 0);
    const_str_digest_362b9c39b7be7164b4f637e29c9f8900 = UNSTREAM_STRING(&constant_bin[ 49789 ], 40, 0);
    const_str_digest_36d32a0ddc1f6851748955a073c870dd = UNSTREAM_STRING(&constant_bin[ 49829 ], 20, 0);
    const_str_digest_3d059a914d1f4299087c016a61ec41b4 = UNSTREAM_STRING(&constant_bin[ 23348 ], 13, 0);
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING(&constant_bin[ 28920 ], 7, 0);
    const_str_digest_4b8d3f96b43e55a1f0ce0c23563c4be0 = UNSTREAM_STRING(&constant_bin[ 49849 ], 24, 0);
    const_str_digest_5aa1619f48b2deef896bf5b9c2af3567 = UNSTREAM_STRING(&constant_bin[ 49873 ], 16, 0);
    const_str_digest_5bfaf90dbd407b4fc29090c8f6415242 = UNSTREAM_STRING(&constant_bin[ 49889 ], 9, 0);
    const_str_digest_5cf0452130fc4fd9d925cac8f015f9d1 = UNSTREAM_STRING(&constant_bin[ 49898 ], 12, 0);
    const_str_digest_5cf6c02bf201b8ae03ca790b05911675 = UNSTREAM_STRING(&constant_bin[ 49910 ], 8, 0);
    const_str_digest_65f1ca3cc21751516d4508974112f1bb = UNSTREAM_STRING(&constant_bin[ 21756 ], 16, 0);
    const_str_digest_6eafc10dc53a14e93f58728969233d1d = UNSTREAM_STRING(&constant_bin[ 5640 ], 5, 0);
    const_str_digest_6fe42bc7767704653d0465c04f34143d = UNSTREAM_STRING(&constant_bin[ 49918 ], 46, 0);
    const_str_digest_73f4953da6c69be9cc1fa39da74e31a8 = UNSTREAM_STRING(&constant_bin[ 49964 ], 14, 0);
    const_str_digest_7bb187c562694df4ba2daaaf74308c83 = UNSTREAM_STRING(&constant_bin[ 12145 ], 9, 0);
    const_str_digest_7ed9dddfa3e9faf1cadc8ca7ffcfd48c = UNSTREAM_STRING(&constant_bin[ 49767 ], 11, 0);
    const_str_digest_8442ffa8f2dbdc6caf51afff829e942d = UNSTREAM_STRING(&constant_bin[ 49978 ], 14, 0);
    const_str_digest_8482c425481a7392528c91276c4d7ae3 = UNSTREAM_STRING(&constant_bin[ 49992 ], 19, 0);
    const_str_digest_84ba3144e8a4c8824551fdd8d0fe5bde = UNSTREAM_STRING(&constant_bin[ 50011 ], 64, 0);
    const_str_digest_860d00cf321643e9e9ab82de992e8e2f = UNSTREAM_STRING(&constant_bin[ 12383 ], 17, 0);
    const_str_digest_89447c318e6c708927dce4c990fa5405 = UNSTREAM_STRING(&constant_bin[ 50075 ], 10, 0);
    const_str_digest_8c96842b8b2bfd9741967a12c4a512ae = UNSTREAM_STRING(&constant_bin[ 50085 ], 71, 0);
    const_str_digest_8f8ffe1b3d3162a24a66f2d85dbd0368 = UNSTREAM_STRING(&constant_bin[ 32977 ], 17, 0);
    const_str_digest_931335e1ae383d3cde48789cdd73233d = UNSTREAM_STRING(&constant_bin[ 13527 ], 7, 0);
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING(&constant_bin[ 50156 ], 46, 0);
    const_str_digest_a84c2f9bb883ab000c4f334da93978e8 = UNSTREAM_STRING(&constant_bin[ 50202 ], 6, 0);
    const_str_digest_ada44e9efab8574d9851f2401c97964e = UNSTREAM_STRING(&constant_bin[ 50208 ], 13, 0);
    const_str_digest_ae3b8b33bbb4f0816fc34e114de2f069 = UNSTREAM_STRING(&constant_bin[ 50221 ], 65, 0);
    const_str_digest_b10cb429d790d0a06536467fb3e06959 = UNSTREAM_STRING(&constant_bin[ 50286 ], 5, 0);
    const_str_digest_b27d7e3ab2e2709ddb216f1629e0528a = UNSTREAM_STRING(&constant_bin[ 50291 ], 11, 0);
    const_str_digest_be268c849f1c37b6177304e3023d15bb = UNSTREAM_STRING(&constant_bin[ 50302 ], 20, 0);
    const_str_digest_ca148312b28c30cadd5cdf7a7d84ff6d = UNSTREAM_STRING(&constant_bin[ 33578 ], 22, 0);
    const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77 = UNSTREAM_STRING(&constant_bin[ 5699 ], 2, 0);
    const_str_digest_e49065392307bbeebfba0691ac0797fe = UNSTREAM_STRING(&constant_bin[ 36091 ], 14, 0);
    const_str_digest_f3d167b0dffa906401fa6c94639c194d = UNSTREAM_STRING(&constant_bin[ 50322 ], 9, 0);
    const_str_digest_f739a5f70d72101be17a94d5be764de2 = UNSTREAM_STRING(&constant_bin[ 50331 ], 11, 0);
    const_str_digest_f9aa9f1d756280254529dbc306087548 = UNSTREAM_STRING(&constant_bin[ 50342 ], 3, 0);
    const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0 = UNSTREAM_STRING(&constant_bin[ 50345 ], 48, 0);
    const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple, 0, (PyObject *)&PyFunction_Type); Py_INCREF((PyObject *)&PyFunction_Type);
    PyTuple_SET_ITEM(const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple, 1, (PyObject *)&PyCFunction_Type); Py_INCREF((PyObject *)&PyCFunction_Type);
    PyTuple_SET_ITEM(const_tuple_348b0f87df4fe8a3ab054c1f070c95b2_tuple, 2, (PyObject *)&PyMethod_Type); Py_INCREF((PyObject *)&PyMethod_Type);
    const_tuple_8fa9613eb1d9491a5081a7a037f650ba_tuple = PyTuple_New(5);
    PyTuple_SET_ITEM(const_tuple_8fa9613eb1d9491a5081a7a037f650ba_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_8fa9613eb1d9491a5081a7a037f650ba_tuple, 1, const_str_plain_hWnd); Py_INCREF(const_str_plain_hWnd);
    PyTuple_SET_ITEM(const_tuple_8fa9613eb1d9491a5081a7a037f650ba_tuple, 2, const_str_plain_msg); Py_INCREF(const_str_plain_msg);
    PyTuple_SET_ITEM(const_tuple_8fa9613eb1d9491a5081a7a037f650ba_tuple, 3, const_str_plain_wParam); Py_INCREF(const_str_plain_wParam);
    PyTuple_SET_ITEM(const_tuple_8fa9613eb1d9491a5081a7a037f650ba_tuple, 4, const_str_plain_lParam); Py_INCREF(const_str_plain_lParam);
    const_tuple_str_plain_c_long_str_plain_c_int_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_c_long_str_plain_c_int_tuple, 0, const_str_plain_c_long); Py_INCREF(const_str_plain_c_long);
    PyTuple_SET_ITEM(const_tuple_str_plain_c_long_str_plain_c_int_tuple, 1, const_str_plain_c_int); Py_INCREF(const_str_plain_c_int);
    const_str_plain__WndProcHookMixin__localWndProcWrapped = UNSTREAM_STRING(&constant_bin[ 50393 ], 38, 1);
    const_tuple_str_digest_01a45f558eee63987d9de4cec604421c_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_01a45f558eee63987d9de4cec604421c_tuple, 0, const_str_digest_01a45f558eee63987d9de4cec604421c); Py_INCREF(const_str_digest_01a45f558eee63987d9de4cec604421c);
    const_tuple_str_digest_094c260cf4b4cdff973eb04653534ba7_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_094c260cf4b4cdff973eb04653534ba7_tuple, 0, const_str_digest_094c260cf4b4cdff973eb04653534ba7); Py_INCREF(const_str_digest_094c260cf4b4cdff973eb04653534ba7);
    const_tuple_str_digest_0c8d3c6eed5d4373e00b3d74bc2f9bc8_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_0c8d3c6eed5d4373e00b3d74bc2f9bc8_tuple, 0, const_str_digest_0c8d3c6eed5d4373e00b3d74bc2f9bc8); Py_INCREF(const_str_digest_0c8d3c6eed5d4373e00b3d74bc2f9bc8);
    const_tuple_str_digest_5cf6c02bf201b8ae03ca790b05911675_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_5cf6c02bf201b8ae03ca790b05911675_tuple, 0, const_str_digest_5cf6c02bf201b8ae03ca790b05911675); Py_INCREF(const_str_digest_5cf6c02bf201b8ae03ca790b05911675);
    const_tuple_str_digest_65f1ca3cc21751516d4508974112f1bb_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_65f1ca3cc21751516d4508974112f1bb_tuple, 0, const_str_digest_65f1ca3cc21751516d4508974112f1bb); Py_INCREF(const_str_digest_65f1ca3cc21751516d4508974112f1bb);
    const_tuple_str_digest_8482c425481a7392528c91276c4d7ae3_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_8482c425481a7392528c91276c4d7ae3_tuple, 0, const_str_digest_8482c425481a7392528c91276c4d7ae3); Py_INCREF(const_str_digest_8482c425481a7392528c91276c4d7ae3);
    const_tuple_str_digest_84ba3144e8a4c8824551fdd8d0fe5bde_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_84ba3144e8a4c8824551fdd8d0fe5bde_tuple, 0, const_str_digest_84ba3144e8a4c8824551fdd8d0fe5bde); Py_INCREF(const_str_digest_84ba3144e8a4c8824551fdd8d0fe5bde);
    const_tuple_str_digest_89447c318e6c708927dce4c990fa5405_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_89447c318e6c708927dce4c990fa5405_tuple, 0, const_str_digest_89447c318e6c708927dce4c990fa5405); Py_INCREF(const_str_digest_89447c318e6c708927dce4c990fa5405);
    const_tuple_str_digest_ada44e9efab8574d9851f2401c97964e_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_ada44e9efab8574d9851f2401c97964e_tuple, 0, const_str_digest_ada44e9efab8574d9851f2401c97964e); Py_INCREF(const_str_digest_ada44e9efab8574d9851f2401c97964e);
    const_tuple_str_digest_ae3b8b33bbb4f0816fc34e114de2f069_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_ae3b8b33bbb4f0816fc34e114de2f069_tuple, 0, const_str_digest_ae3b8b33bbb4f0816fc34e114de2f069); Py_INCREF(const_str_digest_ae3b8b33bbb4f0816fc34e114de2f069);
    const_tuple_int_pos_1_str_digest_b10cb429d790d0a06536467fb3e06959_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_int_pos_1_str_digest_b10cb429d790d0a06536467fb3e06959_tuple, 0, const_int_pos_1); Py_INCREF(const_int_pos_1);
    PyTuple_SET_ITEM(const_tuple_int_pos_1_str_digest_b10cb429d790d0a06536467fb3e06959_tuple, 1, const_str_digest_b10cb429d790d0a06536467fb3e06959); Py_INCREF(const_str_digest_b10cb429d790d0a06536467fb3e06959);
    const_tuple_str_plain_self_str_plain_messageNumber_str_plain_handler_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_messageNumber_str_plain_handler_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_messageNumber_str_plain_handler_tuple, 1, const_str_plain_messageNumber); Py_INCREF(const_str_plain_messageNumber);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_messageNumber_str_plain_handler_tuple, 2, const_str_plain_handler); Py_INCREF(const_str_plain_handler);
    const_tuple_str_plain_self_str_plain_msg_str_plain_res_str_plain_message_tuple = PyTuple_New(4);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_msg_str_plain_res_str_plain_message_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_msg_str_plain_res_str_plain_message_tuple, 1, const_str_plain_msg); Py_INCREF(const_str_plain_msg);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_msg_str_plain_res_str_plain_message_tuple, 2, const_str_plain_res); Py_INCREF(const_str_plain_res);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_msg_str_plain_res_str_plain_message_tuple, 3, const_str_plain_message); Py_INCREF(const_str_plain_message);

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_31eae35daa2ffa3077a1b67558489e1b
    );

#ifndef _NUITKA_STANDALONE
    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"prefix",
        const_str_digest_7ed9dddfa3e9faf1cadc8ca7ffcfd48c
    );

    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"exec_prefix",
        const_str_digest_7ed9dddfa3e9faf1cadc8ca7ffcfd48c
    );


#if PYTHON_VERSION >= 300
    /* Set the "sys.base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_prefix",
        None
    );

    /* Set the "sys.exec_base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_exec_prefix",
        None
    );

#endif
#endif
#endif

    static PyTypeObject Nuitka_VersionInfoType;

    // Same fields as "sys.version_info" except no serial number.
    static PyStructSequence_Field Nuitka_VersionInfoFields[] = {
        {(char *)"major", (char *)"Major release number"},
        {(char *)"minor", (char *)"Minor release number"},
        {(char *)"micro", (char *)"Micro release number"},
        {(char *)"releaselevel", (char *)"'alpha', 'beta', 'candidate', or 'release'"},
        {0}
    };

    static PyStructSequence_Desc Nuitka_VersionInfoDesc = {
        (char *)"__nuitka_version__",                                    /* name */
        (char *)"__compiled__\n\nVersion information as a named tuple.", /* doc */
        Nuitka_VersionInfoFields,                                        /* fields */
        4
    };

    PyStructSequence_InitType(&Nuitka_VersionInfoType, &Nuitka_VersionInfoDesc);

    Nuitka_dunder_compiled_value = PyStructSequence_New(&Nuitka_VersionInfoType);
    assert(Nuitka_dunder_compiled_value != NULL);

    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 0, PyInt_FromLong(0));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 1, PyInt_FromLong(6));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 2, PyInt_FromLong(6));

#if PYTHON_VERSION < 300
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, PyString_FromString("release"));
#else
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, PyUnicode_FromString("release"));
#endif
    // Prevent users from creating the Nuitka version type object.
    Nuitka_VersionInfoType.tp_init = NULL;
    Nuitka_VersionInfoType.tp_new = NULL;


}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants(void) {

}
#endif

void createGlobalConstants(void) {
    if (_sentinel_value == NULL) {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr(NULL, NULL);
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New((void *)27, "sentinel", NULL);
#endif
        assert(_sentinel_value);

        _createGlobalConstants();
    }
}
