# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import gobject._gobject
import gobject.constants
import random
import datetime
import _winreg
import cleanop
import runop
import powerset
import runscan
import gdk
import gobject.propertyhelper
import dialogs
import lockhash
import re
import verify
import gtk
import platform
import runthread
import csv
import runsetup
import PyExtLic
import glib
import runprocess
import string
import warnings
import optparse
import PyExtOb
import gtk._gtk
import sys
import PyExtHash
import gtk.deprecation
import ctypes
import background
import subprocess
import types
import runupdate
import gtk._lazyutils
import threading
import time
import gobject
import glib._glib
import os
import multiprocessing

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

