#!/bin/bash

# Source from the same directory as this script
cur=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${cur}/Bright_Plaza_customizations.sh"


function delete_password {
     delete_SED_keychain_password_from_system_keychain
}

function main {
    if SED_keychain_exists
    then
        KEYCHAIN_PASSWORD="$( read_SED_keychain_password_from_system_keychain )" ||
            fail "finding System keychain item \"${KEYCHAIN_PASSWORD_LABEL}\""  $?
        unlock_SED_keychain ||
            fail "unlocking \"${KEYCHAIN_PATH}\""  $?
        delete_SED_keychain ||
            fail "deleting \"${KEYCHAIN_PATH}\""  $?
    fi
    if [ -n "${KEYCHAIN_PASSWORD}" ]
    then
        delete_password ||
            fail "deleting System keychain item \"${KEYCHAIN_PASSWORD_LABEL}\""  $?
    fi       
}

main
