#!/bin/bash
# set -xv

export CHAIN_LINKS_LIB="${CHAIN_LINKS_LIB-"${HOME}/bin/chain_links"}"
export CHAIN_DIR="$(realpath "$(dirname "$(realpath "${BASH_SOURCE-$0}")")")"
export CHAIN_CURRENT_LINK_SYMLINK_FILENAME="${CHAIN_DIR}/current_link"
export LINKS_DIR="${CHAIN_DIR}/links.d"
export CHAIN_AUTOSTARTS=no
export CHAIN_AUTORUNS=yes
export CHAIN_IS_CIRCULAR=no

export sleepy_time=5
export last_time=$((1+$sleepy_time))
