#!/bin/bash
# Source Utility_functions.sh from the same directory as this script
cur=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${cur}/Utility_functions.sh"

identity="$1"
shift
pwd="$1"
>/dev/null sudo security import "$identity" -k ${SYSTEM_KEYCHAIN_PATH} -f pkcs12 -P "$pwd"  -A

