#!/bin/bash

# Source from the same directory as this script
cur=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${cur}/Bright_Plaza_customizations.sh"


function keychain_exists {
    [ -f "${KEYCHAIN_PATH}" ]
}

function get_password {
      read_keychain_password_from_system_keychain ||
          fail "finding System keychain item \"${KEYCHAIN_PASSWORD_LABEL}\""  $?
}

function delete_password {
     delete_keychain_password_from_system_keychain
}

function main {
    if keychain_exists
    then
        KEYCHAIN_PASSWORD="$( get_password )"
        unlock_keychain || fail "unlocking \"${KEYCHAIN_PATH}\""  $?
        delete_keychain || fail "deleting \"${KEYCHAIN_PATH}\""  $?
    fi
    if [ -n "${KEYCHAIN_PASSWORD}" ]
    then
        delete_password || fail "deleting System keychain item \"${KEYCHAIN_PASSWORD_LABEL}\""  $?
    fi       
}

main
