#!/bin/bash
set -x
# Build a custom bootable image for BIOS machines
## define releases for tools
. conf
VERSIONINFO=`git describe --dirty`
BUILDTYPE=Release
BUILDIMG=LINUXPBA${BUILDTYPE}-${VERSIONINFO}.img
if [ "$BUILDTYPE" == "Debug" ] || [ "$BUILDTYPE" == "Release" ] ; then
            echo "Building " $BUILDTYPE "image"
	else
	    echo "You must select Debug|Release"
	    exit		
fi

# Start fresh
## check that everything is available
[ -f scratch/${SYSLINUX}/bios/mbr/mbr.bin -a \
  -x scratch/${SYSLINUX}/bios/extlinux/extlinux -a \
  -f scratch/buildroot/32bit/images/bzImage  -a \
  -f scratch/buildroot/32bit/images/rootfs.cpio.xz  -a \
  -x scratch/buildroot/32bit/target/sbin/linuxpba  -a \
  -x scratch/buildroot/32bit/target/sbin/sedutil-cli  -a \
  -f buildroot/syslinux.cfg \
  ] || { echo " prereqs are not available "; exit 1; }
#
sudo rm -rf LINUXPBA${BUILDTYPE} ; mkdir LINUXPBA${BUILDTYPE} ; cd LINUXPBA${BUILDTYPE}
dd if=/dev/zero of=${BUILDIMG} bs=1M count=32
(echo o;echo n;echo p;echo 1;echo"";echo "";echo "";echo a;echo 1;echo w) | fdisk ${BUILDIMG}
dd if=../scratch/${SYSLINUX}/bios/mbr/mbr.bin of=${BUILDIMG} count=1 conv=notrunc bs=512
LOOPDEV=`sudo losetup --show -f -o 1048576 ${BUILDIMG}`
sudo mkfs.ext4 $LOOPDEV -L ${BUILDTYPE}-${VERSIONINFO}
mkdir image
sudo mount $LOOPDEV image
sudo chmod 777 image
sudo mkdir -p image/boot/extlinux
sudo ../scratch/${SYSLINUX}/bios/extlinux/extlinux --install image/boot/extlinux
sudo cp ../scratch/buildroot/32bit/images/bzImage  image/boot/extlinux/
sudo cp ../scratch/buildroot/32bit/images/rootfs.cpio.xz image/boot/extlinux/
sudo cp ../buildroot/syslinux.cfg image/boot/extlinux/extlinux.conf
sudo umount image
sudo losetup -d $LOOPDEV
gzip ${BUILDIMG}
