#!/bin/bash
set -x
# Build a custom bootable image for BIOS machines
## define releases for tools
. conf
VERSIONINFO=`git describe --dirty`  || VERSIONINFO=tarball
BUILDTYPE=BIOS32
BUILDIMG=${BUILDTYPE}-${VERSIONINFO}.img

## check that everything is available
chkpre -f scratch/${SYSLINUX}/bios/mbr/mbr.bin
chkpre -x scratch/${SYSLINUX}/bios/extlinux/extlinux
chkpre -f scratch/buildroot/32bit/images/bzImage
chkpre -f scratch/buildroot/32bit/images/rootfs.cpio.xz
chkpre -x scratch/buildroot/32bit/target/usr/sbin/linuxpba
chkpre -x scratch/buildroot/32bit/target/usr/sbin/sedutil-cli
chkpre -f buildroot/syslinux.cfg
#
sudo rm -rf ${BUILDTYPE} ; mkdir ${BUILDTYPE} ; cd ${BUILDTYPE}
dd if=/dev/zero of=${BUILDIMG} bs=1M count=32
(echo o;echo n;echo p;echo 1;echo "";echo "";echo "";echo a;echo 1;echo w) | fdisk ${BUILDIMG}
dd if=../scratch/${SYSLINUX}/bios/mbr/mbr.bin of=${BUILDIMG} count=1 conv=notrunc bs=512
LOOPDEV=`sudo losetup --show -f -o 1048576 ${BUILDIMG}`
sudo mkfs.ext4 $LOOPDEV -L ${BUILDTYPE}
mkdir image
sudo mount $LOOPDEV image
sudo chmod 777 image
sudo mkdir -p image/boot/extlinux
sudo ../scratch/${SYSLINUX}/bios/extlinux/extlinux --install image/boot/extlinux
sudo cp ../scratch/buildroot/32bit/images/bzImage  image/boot/extlinux/
sudo cp ../scratch/buildroot/32bit/images/rootfs.cpio.xz image/boot/extlinux/
sudo cp ../buildroot/syslinux.cfg image/boot/extlinux/extlinux.conf
sudo mkdir -p image/.fseventsd
sudo touch image/.fseventsd/no-log
sudo umount image
sudo losetup -d $LOOPDEV
gzip ${BUILDIMG}
