#!/bin/sh
# Build a custom UEFI linux based PBA image

set -xe

## define releases for tools
. ./conf
VERSIONINFO=$(git describe --dirty || echo tarball)
BUILDTYPE=UEFI64
BUILDIMG=${BUILDTYPE}-${VERSIONINFO}.img

## check that everything is available
EFI_FILE="scratch/${SYSLINUX}/efi64/efi/syslinux.efi"
IMAGE_FILES="scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64
    scratch/buildroot/64bit/images/bzImage
    scratch/buildroot/64bit/images/rootfs.cpio.xz
    scratch/buildroot/64bit/target/sbin/linuxpba
    scratch/buildroot/64bit/target/sbin/sedutil-cli
    buildroot/syslinux.cfg"
for f in $EFI_FILE $IMAGE_FILES; do
    if [ ! -f "$f" ]; then
        echo " prereqs are not available "
        exit 1
    fi
done

# Start fresh
rm -rf -- "${BUILDTYPE}"
mkdir -- "${BUILDTYPE}"

# make an image file
truncate -s32M "${BUILDTYPE}/$BUILDIMG"
sgdisk -n0:0:0 -t0:ef00 "${BUILDTYPE}/$BUILDIMG"
LOOPDEV=$(sudo losetup --partscan --show -f "${BUILDTYPE}/$BUILDIMG")
trap 'sudo losetup -d $LOOPDEV' EXIT
sudo mkfs.vfat "${LOOPDEV}p1" -n ${BUILDTYPE}
mkdir -- "${BUILDTYPE}/image"
sudo mount "${LOOPDEV}p1" "${BUILDTYPE}/image"
trap 'sudo umount ${BUILDTYPE}/image; sudo losetup -d $LOOPDEV' EXIT
sudo mkdir -p -- "${BUILDTYPE}/image/EFI/boot"
sudo cp "$EFI_FILE" "${BUILDTYPE}/image/EFI/boot/bootx64.efi"
# shellcheck disable=SC2086
sudo cp -- $IMAGE_FILES "${BUILDTYPE}/image/EFI/boot/"
gzip "${BUILDTYPE}/$BUILDIMG"
