#!/bin/bash
#  Setup versions for image components
#  This script should be sourced by the other scripts
TINYCORE=Core-6.3.iso
SYSLINUX=syslinux-6.03
TCDISTRO=http://distro.ibiblio.org/tinycorelinux/6.x/x86/
