#!/bin/bash

# Enable all commands in the current folder
export PATH="$(pwd):${PATH}"

# Clear out derived files for a clean build
clean_out_DerivedData SEDTools

# Become sudo-ready if necessary
sudo -p 'Enter admin password now for sudo invocations during build ... ' true

# Continue on with the make_tools script
exec make_tools "${@}"
