#!/bin/bash 
# set -xv
. driver_info
[[ -d "${DRIVER_BUNDLE_PATH}" ]] || echo 2>&1 "Could not find kext bundle ${DRIVER_BUNDLE_PATH}" && exit 1
2>/dev/null kmutil print-diagnostics -pv "${DRIVER_BUNDLE_PATH}"
