#!/bin/bash -xv
sudo security -v delete-certificate -t -c "Bright Plaza, Inc. SED Server"  /Library/Keychains/System.keychain
sudo security -v delete-certificate -c "Bright Plaza, Inc. SED Server"  /Library/Keychains/System.keychain
