#!/bin/bash -xv
SED_IDENTITY_PATH='Bright Plaza, Inc. SED Server.p12'
/Users/scott/Library/Developer/Xcode/DerivedData/TLSTool-frewowfonukeqzfxixapbcyworom/Build/Products/Debug/TLSTool s_server \
    -identityFile "${SED_IDENTITY_PATH}" \
    -authenticate none

                                                                                                            
